Geometry tutorial
gazprom-neft/seismiqb pull request #135
Opened 2021-09-07 13:04 UTC by HollowPrincess

2021-09-09 13:55 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +        n_repeats_slide : int, optional
one of `n` and `repeats` is redundant, they mean the same thing

2021-09-09 13:55 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +        crop_kwargs = {'mode': 'slide'} if use_cache else {}
Not documented and counter-intuitive, why that is the behaviour

2021-09-09 13:55 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +        start = getrusage(RUSAGE_SELF)[0] # user time in seconds
Please, leave code comments for logical blocks

2021-09-09 13:55 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +        start = getrusage(RUSAGE_SELF)[0] # user time in seconds
The fact that you use `user` time instead of `wall` or `system` should be in documentation.
Better yet, you should report `user`, `system` and `wall` timings in a resulting dictionary

2021-09-09 13:55 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +            axis = rng.integers(low=0, high=3)
Should we add the `projections` parameter?

2021-09-09 13:55 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +            shape = rng.integers(low=(5, 5, 5), high=(200, 200, 200))
Make a parameter

2021-09-09 13:55 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +            locations = [slice(start_, np.clip(start_+shape_, 0, max_shape))
Clip makes the crop smaller

2021-09-09 13:55 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +        self.reset_cache()
It should be called before timing crop loading

2021-09-13 13:12 UTC, HollowPrincess commented on seismiqb/src/geometry/base.py
> +            locations = [slice(start_, np.clip(start_+shape_, 0, max_shape))
You are right. It is important because locations must be inside a cube. If ```start_+shape_``` is more than ```max_shape``` we will catch an error.

2021-09-13 17:27 UTC, HollowPrincess commented on seismiqb/src/geometry/base.py
> +        crop_kwargs = {'mode': 'slide'} if use_cache else {}
I commented it, I hope now it is clear.

2021-09-23 10:17 UTC, cdtn commented
The language used in a notebook is kinda obscured. We've got other important things to do for now, but once it should be corrected.

Also, the notebook itself is really long. It describes the SEG-Y format itself, data loading, caching, timing, plotting, and so on. As for me, the last part about conversion to other file formats should be moved to a separate notebook. That notebook on geometry conversion should explain, why one should prefer one format instead of the other.

2021-09-24 12:14 UTC, akoryagin requested changes

2021-09-24 13:28 UTC, HollowPrincess commented on seismiqb/src/geometry/base.py
>  import h5py
Ok

2021-09-27 09:31 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +        projections : sequence of int, optional
default `ixh` would work just fine

2021-09-27 09:31 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +        """Calculate average data loading timings (in ms) in user, system and wall mode for slides and crops.
space

2021-09-27 09:31 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +    def benchmark(self, n_slide=300, projections=(0, 1, 2),
Why three lines for the method signature?

2021-09-27 09:31 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +            'wall': user_slide_timings + system_slide_timings
that is not always the case, is not it?

2021-09-27 09:31 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +        user_slide_timings = 1000 * (end[0] - start[0]) / n_slide
no need for variable, can directly write to dictionary

2021-10-04 08:16 UTC, SergeyTsimfer approved these changes

2021-10-04 08:16 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +        projections_seq = []
why do you need this? `parse_axis` method can work with letter-defined axes

2021-10-04 08:47 UTC, HollowPrincess commented on seismiqb/src/geometry/base.py
> +        projections_seq = []
It is important for the case of a string with multiple letters:
![image](https://user-images.githubusercontent.com/21172482/135820989-2f2512b1-7e43-4dd8-9485-cfc13d2c86c8.png)

2021-10-04 12:48 UTC, SergeyTsimfer approved these changes

2021-10-04 12:49 UTC, merged