Horizon restructuring
gazprom-neft/seismiqb pull request #150
Opened 2021-11-08 11:25 UTC by HollowPrincess

2021-11-09 13:09 UTC, SergeyTsimfer requested changes

2021-11-09 13:09 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +    def file_to_points(cls, path):
And this

2021-11-11 14:58 UTC, HollowPrincess commented on seismiqb/src/field/base.py
> +    def from_points(self, points, transform=False, verify=True, dst='points', **kwargs):
The `dump_charisma` is here, so I want to have methods to open a charisma file without horizon instantiation.

2021-11-11 15:34 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +        matrix = np.full(shape=shape, fill_value=fill_value, dtype=dtype)
make it `field.shape` with `np.nan`s and `dtype=np.float32`

2021-11-11 15:34 UTC, SergeyTsimfer commented on seismiqb/src/labels/horizon.py
> +        points = self.field.cubic_to_lines(copy(self.points))
make `cubic_to_lines` method part of `Field.dump_charisma`

2021-11-17 07:17 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +        if dtype is int:
`np.int32` everywhere

2021-11-17 07:17 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +        print(name)
hi

2021-11-17 07:17 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +         # Cubic to lines
Make it a separate method once again

2021-11-17 07:17 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +        # Transform to cubic coordinates, if needed
Make it a separate method once again

2021-11-22 13:40 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +    def dump_matrix(self, matrix, path, transform=None):
That should be in `Horizon`

2021-11-22 13:40 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +    def prepare_points(self, points, transform=False, verify=True, **kwargs):
Make it one big function `load_charisma`, as a pair to `dump_charisma`, that opens and reads `points` from the supplied file, applies `line_to_cubic` transform, and verifies that all of the points are with cube shape bounds.
The `points to matrix` transform should be separate.

So, the field would have `lines_to_cubic/cubic_to_lines` transformations, as well as `is_charisma_like`, `load_charisma` and `dump_charisma` methods

2021-11-24 11:24 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +        df = pd.DataFrame(points, columns=Horizon.COLUMNS)
use `REDUCED_CHARISMA_SPEC`

2021-11-24 11:24 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +                            '.log', '.txt', '.torch'])
fix indentation

2021-11-24 11:24 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +            if max([path.endswith(ext) for ext in bad_extensions]):
no need for square brackets

2021-11-24 11:24 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +            Whether the dumped data is data in the points (N, 3) or matrix (i_lines, x_lines) format.
Even this docstring suggests that the better parameter would be `format='points'`

2021-11-24 11:24 UTC, SergeyTsimfer commented on seismiqb/src/labels/horizon.py
> +        fill_value = fill_value if fill_value is not None else Horizon.FILL_VALUE
`fill_value or Horizon.FILL_VALUE`?

2021-11-24 11:24 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +        return_points : bool
`format='points'`?

2021-11-24 11:24 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +        name : str
Not used

2021-11-24 11:24 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +            Path to a file to import matrix from.
Now that is a confusing docstring

2021-11-24 11:24 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +            Output matrix dtype.
Why is it called matrix everywhere? CHARISMA is not about matrices

2021-11-24 11:24 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +        matrix = Horizon.points_to_matrix(points=points, i_min=i_min, x_min=x_min,
You would want to create a `full_matrix`, not a reduced matrix from the Horizon class. 
Don't reuse `Horizon.*_to_*` static methods: it would be easier to read those two lines here

2021-11-24 11:24 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +        """ Save matrix as (N, 3) array of points to a disk in CHARISMA-compatible format.
Again, it does not have to be a matrix

2021-12-06 14:23 UTC, SergeyTsimfer approved these changes

2021-12-06 14:23 UTC, SergeyTsimfer commented on seismiqb/src/field/base.py
> +
Why?

2021-12-06 14:23 UTC, SergeyTsimfer commented on seismiqb/src/labels/horizon.py
> +import os
Why?

2021-12-06 14:57 UTC, HollowPrincess commented
Add renaming ```parse_field``` in ```SeismicGeometry``` ~```extract_field_name```

2021-12-07 09:01 UTC, merged