Add adjust parameter to rotate
gazprom-neft/seismiqb pull request #167
Opened 2022-01-28 14:37 UTC by AlexeyKozhevin

2022-02-08 11:14 UTC, SergeyTsimfer approved these changes

2022-02-09 11:51 UTC, cdtn approved these changes

2022-02-16 07:22 UTC, SergeyTsimfer reviewed
Comments to notebook:
- Rename the file
- Remove autoreload
- Remove mentions of `rotate_axis` -- there is no such method 
- Swap the `demo_pipeline` and lists of components: first define the pipeline, and then the lists
- You don't need `show_roll`, as far as I see. use `show` instead: before that, copy the `indices` argument to it from `show_roll`
- Also, you can show original image and its augmented versions on the same figure
- Just as a safety thing: please, check that the dtype of all augmented images is `np.float32`

2022-02-22 09:39 UTC, SergeyTsimfer requested changes
A gentle ping

2022-02-28 11:31 UTC, AlexeyKozhevin commented on seismiqb/src/crop_batch.py
> +            new_shape = adjust_shape_3d(shape=crop.shape, angle=angle)
Yes

2022-02-28 11:37 UTC, AlexeyKozhevin commented on seismiqb/src/crop_batch.py
> +                crop = crop[..., np.newaxis]
No, `resize` for 3D array of shape `(x, y, 1)` transforms it into `(x', y')` (removes one axis) so I return it

2022-02-28 11:38 UTC, AlexeyKozhevin commented on seismiqb/src/crop_batch.py
> +                crop = crop[..., np.newaxis]
And `crop[..., np.newaxis]` is faster then `crop.reshape(*crop.shape, 1)`

2022-03-04 16:05 UTC, merged