Inspect the `Horizon` class
gazprom-neft/seismiqb pull request #182
Opened 2022-03-29 12:33 UTC by HollowPrincess

2022-04-07 08:03 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +    The main classes of these methods are:
🤔

2022-04-12 14:19 UTC, SergeyTsimfer commented on seismiqb/functional.py
> +        if function.__name__ == 'interpolate':
Ugly
Could be moved to decorator parameters / method defaults. In the latter case, you would need to use `inspect` to get the method signature and merge `method.signature.defaults` with `kwargs`

2022-04-12 14:19 UTC, SergeyTsimfer commented on seismiqb/functional.py
> +        preserve_missings = kwargs.get('preserve_missings', False)
Move to the signature explicitly

2022-04-12 14:28 UTC, SergeyTsimfer commented on seismiqb/functional.py
> +            notnan_neighbors = kernel.size - np.nansum(np.isnan(element))
`np.isnan(element).sum` is enough -- that is a `bool`-dtyped matrix.


Almost sure that a loop like:
```python
from math import isnan

present_neightbours = kernel.size
for e in element:
    if isnan(e):
        present_neightbours -= 1
```
would be faster, although might not be worth it

2022-04-12 14:35 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +            filtering_matrix[:margin, :] = 1
`filtering_matrix[-margin:margin, :] = 1` ?

2022-04-13 10:52 UTC, HollowPrincess commented on seismiqb/functional.py
> +def process_missings(function):
I think this is more about matrices, than about horizons.

2022-04-13 10:52 UTC, HollowPrincess commented on seismiqb/labels/horizon_processing.py
> +            filtering_matrix[:margin, :] = 1
It is not work

2022-04-13 11:14 UTC, HollowPrincess commented on seismiqb/functional.py
> +                nanmax, nanmin = np.nanmax(element), np.nanmin(element)
Is slower (`_inerpolate` - implementation in PR, `new_interpolate` - proposed, matrix shape = (1000, 1000), kernel size =3)

![image](https://user-images.githubusercontent.com/21172482/163168503-0dc81ea1-5b40-45ff-b364-4e0c0a6fd858.png)

2022-04-13 11:17 UTC, HollowPrincess commented on seismiqb/functional.py
> +            notnan_neighbors = kernel.size - np.nansum(np.isnan(element))
Is not faster (_inerpolate - implementation in PR, new_interpolate - proposed, matrix shape (1000, 1000), kernel size 3)
![image](https://user-images.githubusercontent.com/21172482/163168873-b1a0fffd-925f-4d7f-bf34-df14395b4274.png)

2022-04-18 14:18 UTC, SergeyTsimfer requested changes
Each of the `smooth_out, smooth_out_bilateral, interpolate, median_filter` is obscured by a number of unnecessary levels of function calls and decorators and being split across multiple files.

Each of them is the same crystal-clear sequence of actions:
```python
# Parse parameters, e.g. prepare kernel if it is not passed explicitly

# Pre-process self.matrix: change fill_value, apply padding, save the mask of present/absent values (in a separate named variable!)

# Apply some function multiple times

# Post-process the output: strip padding, return fill_values, set correct type

# Set the matrix to a horizon in-place (and reset points storage) or return it explicitly
```

Some parts can be moved to a decorator or become separate methods; nevertheless, it should be clear from reading the code in one place.

Please, think out and write down a cohesive plan before touching actual code. Current working version of functions is really just an MVP of what it should be: a coherent piece of clearly written code.

2022-04-18 14:18 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +    def smooth_out(self, kernel=None, kernel_size=3, iters=1, preserve_missings=True, distance_threshold=5,
Currently, this function works in a sense that it fulfills its intended purpose; yet, it raises a lot of questions about its implementations / usage / interface / beauty:
- starting from signature. Why this order of parameters? `kernel, kernel_size, sigma` should be one after the other, maybe even in `kernel_size, sigma, kernel` order.
- do we even need `preserve_missings` parameter? One can use `interpolate -> smooth_out` to emulate the same, while being more explicit.
- do we even need `kernel` parameter? Probably yes.
- `distance_threshold`. what is the `distance`? be more specific: ~`depth_threshold`
- do we need `**_`? Probably not.
- the implementation definitely calls for moving the body of `smooth_out` to here, especially with the fact that this `smooth_out` function does not do anything but makes a kernel, and re-direct to another (`convolve`) function, which actually once again re-makes the kernel, if not provided, and one more time re-directs to a `_convolve`. The number of `re-directs` in the previous sentence should not be 3.

2022-04-18 14:18 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +    def edge_preserving_smooth_out(self, kernel_size=3, sigma_spatial=0.8, iters=1,
If one tracks down the sequence of re-directs of this function to the core, it becomes clear, that the only difference to the previous one is that it uses `_bilateral_filter` instead of `_convolve`. `smooth_out(..., mode='bilateral/convolve`) looks better and saves a lot of space.

2022-04-19 14:27 UTC, SergeyTsimfer requested changes

2022-04-19 14:27 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_attributes.py
> +    """ Get spikes mask along axis. """
having a `check_line` function and running it twice: `check_line(line) and check_line(line[::-1]` would make things a lot easier

2022-04-19 14:27 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_attributes.py
> +    def get_spikes_mask(self, spike_max_width=7, spike_min_height=5, close_depths_threshold=2, dilation=0):
Please, don't use the `height` word when it regards `depth`

`min/max` are misleading in a way that it is hard to understand, whether `min_height` is minimum allowed depth of a spike or is it the minimum detected depth for a spike to be detected


`width_threshold`, maybe?

`depth1_threshold` / `depth2_threshold`? Those two names force you to look into parameter documentation and don't rely on naming being intuitively clear, which it is not

2022-04-19 14:54 UTC, HollowPrincess commented
Fix geometry tests parametrization

2022-04-22 11:22 UTC, SergeyTsimfer requested changes
Rethink naming of thresholds, please

2022-04-22 11:22 UTC, SergeyTsimfer commented on seismiqb/metrics.py
>      def quality_map(self, quantiles, metric_names=None, computed_metrics=None,
Revert the changes to this file, please. Just make a stub instead of `smooth_out`; we will deal with this right before merging this PR

2022-04-22 11:22 UTC, SergeyTsimfer commented on seismiqb/utils/decorators.py
> +    dilation_iterations : int
`dilation`; default should be `None` or `False`

2022-04-22 11:22 UTC, SergeyTsimfer commented on seismiqb/utils/decorators.py
> +            result[instance.field.zero_traces == 1] = np.nan
All of the other operations in this decorator are applied through `instance` methods, and there is a reason for it.

This forces the `dtype` to be `np.float32`, even if `dtype` argument was passed as any other.

2022-04-22 11:22 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_attributes.py
> +    def get_spikes_mask(self, spike_spatial_maxsize=7, spike_depth_minsize=5, close_depths_threshold=2,
Why previous methods are `*_map`s, and this one is `_mask`?

2022-04-22 11:22 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_attributes.py
> +        We suppose that spikes are huge depth changes with invert depth changes in a fixed size window.
This is very hard to read, and even harder to understand

2022-04-22 11:22 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_attributes.py
> +        spike_depth_minsize : int
`spike_min_depth`?

2022-04-22 11:22 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +            filtering_matrix = binary_dilation(filtering_matrix, structure=np.ones((margin, margin)))
That is wrong: for example, if `margin==1`, this does nothing. You should pass `margin` as `iters` parameter

2022-04-22 11:22 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +        result = self.matrix_smooth_out(matrix=self.matrix, mode=mode, iters=iters,
And also move `njit` functions to here

2022-04-22 11:22 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +        depths_variance_threshold : number
`max_depth_ptp`

2022-04-22 11:30 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_attributes.py
> +        spike_depth_minsize : int
or, better yet, `min_spike_depth` and `max_spike_length`

2022-04-26 10:42 UTC, SergeyTsimfer commented on seismiqb/labels/horizon.py
> +        self.dump_charisma(data=smoothed.points, path=path, format='points', name=self.name, transform=transform)
The idea of this method is to save floating-points number, produced by smoothing out integer values, on disk.

This implementation converts values back to integer and is effectively equivalent to separate method calls `smooth_out(...) -> dump(...)`

2022-04-26 10:42 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +    def thin_out(self, factor=1, threshold=256, inplace=True):
Reposition methods, so that `thin_out` is near `make_carcass/make_holes`

2022-04-26 10:42 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +    def filter_spikes(self, spike_spatial_maxsize=7, spike_depth_minsize=5, close_depths_threshold=2,
If all of the parameters are default to `spikes` attribute, we can not just call `filter('spikes')`, right?

2022-04-26 10:42 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +            - if `preserve_missings=True`, then missing points remain absent in the resulting surface.
There is no such parameter

2022-04-26 10:42 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +            - If the `sigma_range` too low, then no smoothening applied.
That is a comment only to `bilateral`. Indent it

2022-04-26 10:42 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +        In either case it returns a processed horizon instance.
Returning a `float32` matrix if `not inplace` would make lives (yours in particular) a lot easier.

On the other hand, you can try `Horizon(..., dtype=np.float32)` and see if it works

2022-04-26 10:42 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +            kernel = make_gaussian_kernel(kernel_size=kernel_size, sigma=sigma_spatial)
`kernel = kernel if kernel is not None else ...`?

2022-04-29 14:24 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_processing.py
> +        return type(self)(storage=result, i_min=self.i_min, x_min=self.x_min, field=self.field, name=name, dtype=dtype)
Is the dumped horizon actually float?

2022-05-13 11:55 UTC, merged