Fault refactoring
gazprom-neft/seismiqb pull request #205
Opened 2022-07-28 15:09 UTC by AlexeyKozhevin

- `Fault` is no longer a child of `Horizon`!
- Split `Fault` methods into mixins
- Add several tests
- `Fault` can work with one-stick faults
- `show_3d` can plot sticks
- Change `Sampler` logic to work with labels of not comparable sizes

2022-08-01 10:43 UTC, SergeyTsimfer commented on seismiqb/utils/functions.py
> +        if (point[0] >= mask_bbox[0][0]) and (point[0] < mask_bbox[0][1]):
this series of `if`s could be changed to one `if` with `and` in between statements. Should be of same speed due to short circuit evaluation

2022-08-01 10:43 UTC, SergeyTsimfer commented on seismiqb/utils/functions.py
> +    """ Create mask for points inside of the cube. """
I am not sold on this function. It is used only 3 times and not supposed to be used outside library code; for me, it is much easier to see this function code instead of a call to some vague function

2022-08-01 10:43 UTC, SergeyTsimfer commented on seismiqb/samplers.py
> +            labels_weights.append(weights)
Add description of weights (both label-wise and field-wise) to the documentation, please

2022-08-01 10:43 UTC, SergeyTsimfer commented on seismiqb/utils/functions.py
> +    """ Add new points into binary mask. """
Add more about shapes of arguments, so it would be easier to read this code the next time

2022-08-01 10:43 UTC, SergeyTsimfer commented on seismiqb/labels/mixins.py
> +        if zoom:
please, add something like:
```python
if zoom == 'auto':
    zoom = self.compute_auto_zoom(loc, axis, zoom_margin)
```

For horizons, method `compute_auto_zoom` would return something like `(slice(None), slice(self.h_min - zoom_margin, self.h_max + zoom_margin))`, for faults -- same `bbox`, as you used in the `show` method

2022-08-01 10:43 UTC, SergeyTsimfer commented on seismiqb/labels/mixins.py
> +    def show_slide(self, loc, width=None, axis='i', zoom=None, **kwargs):
What about plot, where we have seismic slide (with overlayed labels) and top-view on field with a line indicating the location of the first plot?

2022-08-01 10:43 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault_visualization.py
> +        super().show_slide(loc, **kwargs)
`return `

2022-08-01 10:43 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault_formats.py
> +        """ Remove <<strange>> sticks. """
Describe the list of what is considered `<<strange>>`, so that we can see it without reading code

2022-08-01 10:43 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault_formats.py
> +    """ Mixin to load and dump FaultSticks. """
Both mixins in this file call for more human-readable documentation with explanations of intent behind the logic

2022-08-01 10:43 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault.py
> +    """ Class to represent Fault object. Each fault has 3 representations:
Would like more information about conversion process, cons/pros of each fault representation, where each fault representation is used and best for

2022-08-01 10:43 UTC, SergeyTsimfer commented on seismiqb/labels/__init__.py
> +from .fault import *
😢

2022-08-01 13:23 UTC, AlexeyKozhevin commented on seismiqb/labels/mixins.py
> +    def show_slide(self, loc, width=None, axis='i', zoom=None, **kwargs):
I guess it must be separate PR

2022-08-02 13:21 UTC, cdtn commented on seismiqb/geometry/base.py
> +            mask = self.zero_traces[..., loc]
```suggestion
        mask = self.zero_traces.take(loc, axis)
```

2022-08-02 13:21 UTC, cdtn commented on seismiqb/geometry/export.py
> +                         origin=(0, 0, 0), ilines_offset=1, xlines_offset=1, pbar=False, **kwargs):
why plural?

2022-08-02 13:21 UTC, cdtn commented on seismiqb/labels/fault/__init__.py
> +""" Labeled structures in a seismic volume. """
How about more fault-specific doc?

2022-08-02 13:21 UTC, cdtn commented on seismiqb/labels/fault/fault.py
> +                            dtype=np.int32)
```suggestion
        self.bbox = np.array([[self.i_min, self.i_max],
                              [self.x_min, self.x_max],
                              [self.h_min, self.h_max]],
                             dtype=np.int32)
```

2022-08-02 13:21 UTC, cdtn commented on seismiqb/labels/fault/fault.py
> +            setattr(self, '_'+key, data)
```suggestion
            setattr(self, '_' + key, data)
```

2022-08-02 13:21 UTC, cdtn commented on seismiqb/labels/fault/fault.py
> +                raise AttributeError("`simplices` can't be created.")
Maybe specify some details about absence of both points and sticks in fault instance?

2022-08-02 13:21 UTC, cdtn commented on seismiqb/labels/fault/fault.py
> +        insert_points_into_mask(mask, points, mask_bbox, width=width, axis=1-self.direction)
```suggestion
        insert_points_into_mask(mask, points, mask_bbox, width=width, axis=1 - self.direction)
```

2022-08-02 13:21 UTC, cdtn commented on seismiqb/labels/fault/fault_approximation.py
> +    step = min(sticks_step, len(projections)-1)
```suggestion
    step = min(sticks_step, len(projections) - 1)
```

2022-08-04 13:24 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault_visualization.py
> +    def compute_auto_zoom(self, loc, axis, zoom_margin):
I would rather use this function in `show_slide` directly, if `zoom='auto'`

2022-08-04 13:24 UTC, SergeyTsimfer commented on seismiqb/geometry/base.py
> +    def get_slide_bounds(self, loc, axis=0):
I would rather make it `get_auto_zoom` method, that returns a tuple of slices, directly usable as `zoom` parameter. This way, we can use it everywhere equally

2022-08-04 13:24 UTC, SergeyTsimfer commented on seismiqb/labels/horizon_visualization.py
> +    def compute_auto_zoom(self, loc, axis=None, zoom_margin=20):
`zoom_margin` for horizon should be much bigger

2022-08-08 09:22 UTC, HollowPrincess commented on seismiqb/labels/fault/fault_visualization.py
> +        kwargs = {**kwargs, 'cmap': cmap, 'width': width}
```suggestion
        defaults = {'cmap': ['Greys_r', 'red'], 'width': 5}
        kwargs = {**defaults, **kwargs}
```

2022-08-08 09:22 UTC, HollowPrincess commented on seismiqb/utils/functions.py
> +            (point[2] <  mask_bbox[2][1] + right_margin[2]-1)):
```suggestion
            (point[0] <  mask_bbox[0][1] + right_margin[0] - 1) and
            (point[1] <  mask_bbox[1][1] + right_margin[1] - 1) and
            (point[2] <  mask_bbox[2][1] + right_margin[2] - 1)):
```

2022-08-08 09:50 UTC, HollowPrincess commented on tests/notebooks/fault_test_01_preparation.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    # This notebook contains preparation for Horizon tests
</pre><p>Horizon -&gt; Fault everywhere</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/seismiqb/pull/205/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2022-08-08 09:50 UTC, HollowPrincess commented on tests/notebooks/fault_test_01_preparation.ipynb
> +{
<p>Please, clear all outputs in all notebooks.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/seismiqb/pull/205/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2022-08-08 09:50 UTC, HollowPrincess commented on tests/notebooks/fault_test_02_base.ipynb
> +{
<p>Storage convertation maybe?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/seismiqb/pull/205/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='8'/>

2022-08-08 09:50 UTC, HollowPrincess commented on tests/notebooks/fault_test_02_base.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #10.    assert (fault.simplices == dumped_fault.simplices).all(), f"<code>dump_npz</code> test failed: original and dumped 'simplices' are unequal"
</pre><p>Can <code>fault.simplices</code> be in the float data format? </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/seismiqb/pull/205/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2022-08-08 09:50 UTC, HollowPrincess commented on tests/notebooks/fault_test_02_base.ipynb
> +{
<p>Maybe it would be better to unite this cell with the next? This variable is used only in one test.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gazprom-neft/seismiqb/pull/205/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2022-08-08 09:54 UTC, HollowPrincess requested changes
Please, clear outputs in tests notebooks and rewrite comment lines in tests (on notebooks top and replace `horizon` with `fault`).

2022-08-09 10:15 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault.py
> +    Convertion from sticks to nodes/simplices is extremely obvious.
`...is simply selecting subset of points`

2022-08-09 10:15 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault.py
> +    Convertion from points to sticks is more difficult and proposes that points represent
`and assumes that points are on almost flat 3d plane`

2022-08-09 10:15 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault.py
> +        - npz file with 'points', 'nodes', 'simplices' and 'sticks' or dict with the same keys.
Should be in the beginning

2022-08-09 10:15 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault.py
> +            self.set_direction(direction)
`set_direction(None)` would be more explicit

2022-08-09 10:15 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault.py
> +            source = 'objects'
`dict`?

2022-08-09 10:15 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault.py
> +    def create_stats(self):
`compute_stats`?

2022-08-09 10:15 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault.py
> +    def reset_storage(self, storage):
Do you need this method?

2022-08-09 10:15 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault.py
> +        """ Simplices. """
Please, write more than one word, even if it is a copy from the class docstring

2022-08-09 10:15 UTC, SergeyTsimfer commented on seismiqb/labels/fault/fault.py
> +        return np.prod(self.bbox[:, 1] - self.bbox[:, 0] + 1)
That is a volume of a cuboid, containing the fault. I would expect the `len` of a fault to be the number of its points.

Maybe, name this `max_possible_length`?

2022-08-09 10:15 UTC, SergeyTsimfer commented on seismiqb/samplers.py
> +    baseclass : type
There is no such parameter:)

2022-08-09 10:15 UTC, SergeyTsimfer commented on seismiqb/utils/functions.py
> +def insert_points_into_mask(mask, points, mask_bbox, width, axis):
Should not it be in your `faults` directory?

2022-08-09 10:52 UTC, AlexeyKozhevin commented on seismiqb/labels/fault/fault.py
> +    def reset_storage(self, storage):
If  `points` was created from `sticks` and you wish `sticks` with other step, you can reset them and call.

2022-08-09 11:09 UTC, AlexeyKozhevin commented on tests/notebooks/fault_test_02_base.ipynb
> +{
<p>No</p>

2022-08-09 11:43 UTC, merged