created class for denoising metrics
gazprom-neft/seismiqb pull request #213
Opened 2022-08-19 08:21 UTC by AnnaAltynova

metrics class for denoising performance estimation. contains source - prediction metrics for a batch, fourier power spectrum for an image, and local correlation and similarity maps for denoised image - estimated noise comparison.

2022-08-19 11:31 UTC, akoryagin commented on seismiqb/denoising_metrics.py
> +        x_centered = x - x.mean(axis=1).reshape(-1, 1)
`keepdims=True` in `mean`

2022-08-19 11:31 UTC, akoryagin commented on seismiqb/denoising_metrics.py
> +        """Squared Pearson correlation coeffitient between corresponding rows of 2d input arrays"""
typo: coefficient

2022-08-19 11:31 UTC, akoryagin commented on seismiqb/denoising_metrics.py
> +        return corr ** 2
I don't think the you need to take `corr` squared

2022-08-19 11:31 UTC, akoryagin commented on seismiqb/denoising_metrics.py
> +        images : sequence
Need more info here: sequence of what? Of 2d-arrays - or does it support several channels?

2022-08-19 11:31 UTC, akoryagin commented on seismiqb/denoising_metrics.py
> +        window_shape=[window_size, window_size if n_dims == 2 else 1]
`window_shape = [window_size, window_size if n_dims == 2 else 1]`

2022-08-19 11:31 UTC, akoryagin commented on seismiqb/denoising_metrics.py
> +                                                strides=(0, 8 * window_size**n_dims, 8))
Fix tabulation

2022-08-19 13:14 UTC, HollowPrincess requested changes
Think about the code structure: which methods do we really need and in which view, what API is the most suitable for usecases.
Also, think about more appropriate and clear variable names and docstrings.

2022-08-24 13:33 UTC, AnnaAltynova commented on seismiqb/denoising_metrics.py
> +        predictions = predictions if isinstance(predictions, torch.Tensor) else torch.tensor(predictions)
torchmetrics accepts torch.Tensors only.

2022-09-28 14:24 UTC, merged