Updates in the `Horizon.from_mask` method
gazprom-neft/seismiqb pull request #215
Opened 2022-08-19 14:20 UTC by HollowPrincess

- [ ] Add `mask_map` attribute evaluation into `Horizon.from_mask`
- [ ] Refactor code using [connected_components](https://github.com/seung-lab/connected-components-3d/) library

Benchmarks for connected_components library against old implementation:

On the random generated data
<add>

On the real examples
<add>

2022-08-31 08:54 UTC, AlexeyKozhevin approved these changes

2022-08-31 09:55 UTC, cdtn requested changes

2022-08-31 09:55 UTC, cdtn commented on seismiqb/labels/horizon/attributes.py
> +    def mask_map(self):
'mask_map' name is misleading:
- every horizon attribute is a 'map', so this postfix actually tells nothing about the attribute itself
- as for 'mask', it collides with an alias for 'full_binary_matrix' of the same name and has nothing to do with horizon presence probabilities

'probabilities' or 'presence_probabilities' are better
maybe also add 'proba' alias

2022-08-31 09:55 UTC, cdtn commented on seismiqb/labels/horizon/base.py
> +            Can be one of: 1 or 6 (voxel faces), 2 or 18 (+ edges), 3 or 26 (+ corners).
<details>
<summary>
???
</summary>
<img src="https://user-images.githubusercontent.com/53620809/187650963-ebc782c8-738a-427e-891d-54ec01d881cd.png"></img>
</details>

2022-08-31 10:41 UTC, HollowPrincess commented on seismiqb/labels/horizon/attributes.py
> +    def mask_map(self):
This property is created from values that are saved only in the `Horizon.from_mask` method. The method extracts a horizon from a **mask**. I think, not for all mask types the name 'probabilities' is correct, when the name 'mask_values' is more suitable. The `mask_map` property creates the matrix (map) of these 'mask_values'. The postfix 'map' clarify that the output is a matrix, not a value or array of values.

2022-08-31 10:43 UTC, HollowPrincess commented on seismiqb/labels/horizon/base.py
> +            Can be one of: 1 or 6 (voxel faces), 2 or 18 (+ edges), 3 or 26 (+ corners).
This docstring is highly inspired by the `cc3d.connected_components` method docstring.

2022-08-31 10:55 UTC, HollowPrincess commented on seismiqb/labels/horizon/base.py
> +            Can be one of: 1 or 6 (voxel faces), 2 or 18 (+ edges), 3 or 26 (+ corners).
As alternatives, we can use [surfaces](https://www.sciencedirect.com/topics/computer-science/neighboring-voxels#:~:text=The%20connectivity%20of%20a%20voxel,of%20the%20features%20of%20interest.) or [horizontal and vertical neighbors](https://3d.bk.tudelft.nl/courses/backup/geo1004/2020/data/handout3.1.pdf) instead of faces.

2022-09-02 15:56 UTC, akoryagin approved these changes

2022-09-02 15:56 UTC, akoryagin commented on seismiqb/labels/horizon/attributes.py
> +        raise AttributeError(f'Horizon `{self.displayed_name}` hasn\'t `probabilities` attribute. Check, whether'
`probabilities_` attribute

2022-10-11 11:46 UTC, SergeyTsimfer commented on seismiqb/labels/horizon/base.py
> +            length = len(self.points)
that is a non-existing optimization -- one `getattr` would not change anything

2022-10-11 11:46 UTC, SergeyTsimfer commented on seismiqb/labels/horizon/base.py
> +        if connectivity == 1:
I would set `connectivity=26` in parameters

2022-10-11 11:46 UTC, SergeyTsimfer commented on seismiqb/labels/horizon/base.py
> +                        if save_probabilities:
`if save_probabilities and len(horizon) > 0:`

2022-10-11 11:46 UTC, SergeyTsimfer commented on seismiqb/labels/horizon/base.py
> +                                          horizon.points[:, 2] - origin[2]]
or you can save result of `group_function(coords, values)` to a separate variable

2022-10-11 11:46 UTC, SergeyTsimfer commented on seismiqb/labels/horizon/base.py
> +                        if save_probabilities:
or at least move `horizons.append(horizon)` here

2022-10-11 11:46 UTC, SergeyTsimfer commented on seismiqb/labels/horizon/base.py
> +        self.bbox = np.array([self.i_min, self.i_max,
Keep old `bbox` as it is
Add `raveled_bbox` if you need it

2022-10-11 13:17 UTC, HollowPrincess commented on seismiqb/labels/horizon/base.py
> +                                          horizon.points[:, 2] - origin[2]]
They are not the same: Horizon constructor contains points verification.

2022-10-13 09:40 UTC, HollowPrincess commented on seismiqb/labels/horizon/horizon_extractor.py
> +        #       'slide' ⟶ view on values in the original probability array,
Do we really need 'slide' information?

2022-10-13 09:40 UTC, HollowPrincess commented on seismiqb/labels/horizon/horizon_extractor.py
> +        for item_idx, item_length in Notifier(pbar)(list(item_iterator)[:n]):
What about of returning new prototypes by sequential calls of `make_prototypes`?

2022-10-13 14:22 UTC, SergeyTsimfer commented on seismiqb/labels/horizon/horizon_extractor.py
> +        #       'slide' ⟶ view on values in the original probability array,
For now we don't use it, but it is a view and costs literally nothing

2022-10-17 11:55 UTC, merged