Update accumulator
gazprom-neft/seismiqb pull request #261
Opened 2023-04-10 11:14 UTC by SergeyTsimfer

This PR:
- speeds up some of the inner computations of `RegularGrid` and makes `strides` parameter parse to `crop_shape` by default
- adds SHM type for all accumulators: memory for data is shared across process and can be accessed by its name

2023-04-11 09:58 UTC, AlexeyKozhevin commented on seismiqb/utils/accumulator3d.py
> +                 type_=None, path=None, dataset_kwargs=None, **kwargs):
Rename `type_` to `fmt`

2023-04-13 10:11 UTC, HollowPrincess commented on seismiqb/utils/functions.py
> +    return ''.join(random.choice(chars) for _ in range(size))
Can we have name collisions because of this? Or it is not cruicial?

Maybe we need a numbers generator as a prefix?

2023-04-13 15:33 UTC, AlexeyKozhevin commented on seismiqb/geometry/base.py
> +        slide = self.load_slide(index=index, axis=axis,)
```suggestion
        slide = self.load_slide(index=index, axis=axis)
```

2023-04-13 15:49 UTC, AlexeyKozhevin requested changes

2023-04-13 15:49 UTC, AlexeyKozhevin commented on seismiqb/geometry/base.py
> +        ptps = cv2.dilate(slide, kernel) - cv2.erode(slide, kernel)
Doesn't work with `int8` slides:
![Screenshot 2023-04-13 at 18 48 03](https://user-images.githubusercontent.com/19620584/231814642-823f70bd-c09b-47c2-b50b-e18a3723fd98.png)

2023-04-19 13:59 UTC, HollowPrincess commented on seismiqb/utils/accumulator3d.py
> +    def remove_placeholder(self, name=None, unlink=False):
Looks like `unlink` is a special 'shm' kwarg and doesn't coresspond to other types.
It is unimportant, but I propose to rename `unlink` to `kwargs` and pop it in 'shm' case.

2023-04-19 13:59 UTC, HollowPrincess commented on seismiqb/utils/accumulator3d.py
> +                state[name] = None
Why we doesn't do the same for 'numpy' placeholder?

2023-04-19 13:59 UTC, HollowPrincess commented on seismiqb/utils/accumulator3d.py
> +        return array.astype(np.uint16)
What about `convert_prediction(array, dtype)` method?

2023-04-19 13:59 UTC, HollowPrincess commented on seismiqb/utils/accumulator3d.py
> +            raise ValueError('Dtype should be floating for STD accumulator!')
I think there is should be a check for float subtype on the 439 line or the error message should contain supported dtypes.

2023-04-19 13:59 UTC, HollowPrincess commented on seismiqb/utils/accumulator3d.py
> +
Maybe it would be better to reduce these lines of code with one function `_std_aggregator(counts, data, sum)`?

2023-04-20 14:59 UTC, AlexeyKozhevin approved these changes

2023-04-24 13:17 UTC, HollowPrincess approved these changes

2023-04-24 13:17 UTC, HollowPrincess commented on seismiqb/grids.py
> +        float_types = (float, np.float16, np.float32, np.float64, np.float128)
```python
np.issubdtype(type(variable), np.floating)
```

2023-04-26 14:49 UTC, AlexeyKozhevin commented on seismiqb/geometry/base.py
> +    def get_slide_mask(self, index, axis=0, kernel_size=9, threshold=None, erosion=11):
The function works only with the whole slide but sometimes its needed to proccess some crop from it. Add `locations/ranges/smth`

2023-05-03 15:58 UTC, merged