Better make grid
gazprom-neft/seismiqb pull request #30
Opened 2020-08-18 21:35 UTC by dmylzenova

Prevent SeismicCubeset.make_grid from creating crops in places with zero_traces or on any other condition (e.g. create a grid only in places where horizon exists).

2020-08-18 22:09 UTC, SergeyTsimfer requested changes
Overall looks nice, but being 66 commits behind the master branch is not good.
Also, add enhancements to `make_grid`, proposed in #17: better interface for `ilines_range`, `xlines_range`, `heights_range`. And make so we can use `overlap` integer/sequence instead of `strides` tuple.

2020-08-18 22:09 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +                if np.sum(gaps_matrix[il: il + crop_shape[0],
Are there situations where we would want to remove crops, that don't consist of only meaningful traces?
I guess if there is an overlapping stride, one can see the possibility to do so, but can you add some other examples of usage?

2020-08-18 22:09 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +        # Update ranges to actual ones
I am a user
I ask the `make_grid` method to create a grid for inference for ([100, 500], [600, 700], [800, 1000]) location. I do expect the output array to have the shape of (400, 100, 200).
If you do want to make this optimization, you need to store the left-most upper point and use it later to ~zero-pad your optimized array. Unfortunately, that would not give you any benefits (and even make it almost twice worse memory-wise).

2020-08-20 10:37 UTC, dmylzenova commented on seismiqb/src/cubeset.py
> +        gaps_matrix : ndarray
That is why I didn't call it `filtering_matrix`

2020-08-20 10:59 UTC, dmylzenova commented on seismiqb/src/cubeset.py
> +                if np.sum(gaps_matrix[il: il + crop_shape[0],
> Are there situations where we would want to remove crops, that don't consist of only meaningful traces?
I was thinking about 2 main use case scenarios:
- Filtering zero traces, we don't want crops that consist of zero traces only. But still, we may want crops from the borders with some part of zero traces. This allowed part can be parametrized with `gaps_threshold` (can add a possibility to make it float as crop_shape proportion in [0, 1], btw)
- Horizon enhancement - I think it is also acceptable to have a part of the crop without horizon because we don't want to skip areas next to horizon borders. It is possible to add some shifts of the crop coordinates if we don't want to allow 
any uncovered places and don't want crops that do not consist of meaningful traces only, but I don't think it is a good idea.

> I guess if there is an overlapping stride, one can see the possibility to do so
?

2020-08-20 11:08 UTC, dmylzenova commented on seismiqb/src/cubeset.py
> +        # Update ranges to actual ones
I thought it would be a useful optimization since the resulting crop shape is updated in the grid_info.
But I agree it is not quite straightforward, I'll reverse.

2020-08-24 12:48 UTC, merged