Estuaries
gazprom-neft/seismiqb pull request #31
Opened 2020-08-18 21:44 UTC by akoryagin

## Additions

* method `Horizon.get_array_values` that allows to get the array of values along the horizon (similar to `Horizon.get_cube_values` but cuts values from an external array).

2020-08-18 22:36 UTC, SergeyTsimfer requested changes
I do believe that this `cut_data_along_horizon` function works fine and produces correct results, yet I do have a question.
You have a specification of `WHERE` the array is located (in cubic coordinates): it can be derived from `array_offset` and the shape of a provided array; also, you do know `WHERE` the horizon is located (again, in cubic coordinates). It is exactly the same situation as in `Horizon.add_to_mask` method: we do have two entities that (possible) have an overlap, and we want to add `ones` to the location of a horizon. The only (and I mean it, it is the only) difference is that instead of adding ones to the points where horizon is, you want to retrieve data from an array, so the line 
```
mask[idx_i, idx_x, heights] = alpha
```
in `Horizon.add_to_mask` must be changed to something like
```
background[idx_i, idx_x, np.full_like(heights, j)] = data_chunk[heights, idx_i, idx_x]
```
I copied this line from `Horizon.get_cube_values` method, which does exactly that.

And you can actually easily check if this works: you can create an instance of `SeismicGeometry` from a converted to HDF5 array with predicted estuaries, load horizon, and use `get_cube_values` to obtain the needed result.

Overall, I believe that doing this function with `numpy` approach would be faster and more reasonable at the same time: it also uses the same techniques as pretty much everywhere else in `seismiQB`. Let's leave `numba` as a last resort tool.

2020-08-18 22:36 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def get_array_values(self, array, array_offset=None, dataset=None, width=5, axes=(2, 1, 0)):
Seems like you are looking for the same signature, as `Horizon.from_mask` has: `grid_info` or `shifts`.
Also, the word `offset` is pretty much reserved exclusively for the needs of pre-stack geometries.

2020-08-18 22:36 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        axes : tuple
Do we really need it here? If one wants to transpose, make him do so

2020-08-18 22:36 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        horizon_offset = self.bbox[0, 0], self.bbox[1, 0]
`self.i_min`, `self.x_min`

2020-08-18 22:36 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +    cut_out = np.zeros(array.shape[:2] + (width, ))
Default `dtype` is `float64`, which is undesired.
Also, as the word `cutout` is reserved for something else in our line of work, let's use something else.

2020-08-25 05:48 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +        mask = (surface_level >= 0) & (surface_level < array.shape[-1]) & (surface_level !=
You are creating `width` matrices and store them in memory at the same time: that is inefficient 
Then for each of them, you re-compute `mask` and `where` without reusing the data from previous iterations.
Please, move this function to `Horizon` (as it is not `njit`-decorated, you don't need to have it in a separate file), change shape arrays to integers as they are way easier to understand and don't need tons of weird slices and lists, and retrieve heights to get from array once.

2020-08-25 05:48 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +    result = np.zeros(array.shape[:2] + (width, ))
It is possible for value in `array` to be `0`, so let's make this matrix be filled with `nan`s, and dtype `float32`

2020-09-08 09:24 UTC, roman-kh commented on seismiqb/src/horizon.py
> +                raise ValueError('Either array_shift or dataset with filled grid_info must be supplied!') #pylint: disable=raise-missing-from
Do not disable. Use `from` clause to save the context (see [PEP 3134](https://www.python.org/dev/peps/pep-3134/))

2020-09-08 09:25 UTC, roman-kh commented on models/get_array_funcs.py
> +    args = (horizon_matrix, horizon_offset, array, array_offset, width, -999)
```suggestion
    args = (horizon_matrix, horizon_offset, array, array_offset, width, fill_value)
```

2020-09-12 12:59 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def get_array_values(self, array, array_shift=None, dataset=None, width=5, axes=(2, 1, 0)):
Make ~the same signature, as of `Horizon.from_mask` method: no need for dataset passing

2020-09-12 12:59 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +            try:
No need for `try/except`

2020-09-18 23:34 UTC, SergeyTsimfer approved these changes

2020-09-18 23:34 UTC, merged