Geometry improvements
gazprom-neft/seismiqb pull request #33
Opened 2020-08-19 06:54 UTC by SergeyTsimfer

This PR proposes to:

- change `slices` component of `CropBatch` to `locations`

- change format of each `location` to list of three `slices` (actual instances of `slice`)

- add `__getitem__` to SEG-Y and HDF5 geometries that allows for easier loads

- add `zero_traces` attribute for SEG-Y geometries prior to collecting spatial stats

2020-08-24 16:44 UTC, dmylzenova commented on scripts/horizon_assessment.py
> +                om = HorizonMetrics(other)
That is an unclear two letters naming

2020-08-24 16:44 UTC, dmylzenova commented on seismiqb/src/crop_batch.py
> +            Direction of the cut crop relative to the point. Must be a vector on unit cube.
Not very clear. Provide an example, please.

2020-08-24 16:44 UTC, dmylzenova commented on seismiqb/src/crop_batch.py
> +            Component of batch to store the resulting labels, o/w a storing object.
o/w? -otherwise? one way? output/write?

2020-08-24 16:44 UTC, dmylzenova commented on seismiqb/src/geometry.py
> +        'depth', 'delay', 'sample_rate', 'cube_shape',
I haven't found that, if you already haven't -  can you, please, also store line_cdp transform or a couple of values?

2020-08-24 20:25 UTC, dmylzenova requested changes

2020-08-24 20:25 UTC, dmylzenova commented on seismiqb/src/horizon.py
> +        """ Compute a number of stats on location of `self` relative to the `other` Horizons. """
If you wanted to make it more explanatory, you could do better.

2020-08-24 20:25 UTC, dmylzenova commented on seismiqb/src/geometry.py
> +                    pass
Warnings, if some metadata is missing, wouldn't hurt.

2020-08-24 20:25 UTC, dmylzenova commented on seismiqb/src/geometry.py
> +        # self.file_hdf5 = h5py.File(self.path, mode='r')
Why is it here?

2020-08-25 06:23 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +            Direction of the cut crop relative to the point. Must be a vector on unit cube.
I was actually unable to do so. Do you still use this parameter in your researches?

2020-08-25 06:25 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        h_max = locations[-1].start
Nice catch!

2020-08-25 06:26 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +                background[idx_i, idx_x, np.full_like(heights, j)] = data_chunk[idx_i, idx_x, heights]
The caching of data along the horizon is on the `Metrics` side, as it always was.

2020-08-25 08:59 UTC, dmylzenova commented on seismiqb/src/crop_batch.py
> +            Direction of the cut crop relative to the point. Must be a vector on unit cube.
Now I don't

2020-08-25 21:33 UTC, dmylzenova commented on seismiqb/src/geometry.py
> +        """ Add transform from INLINE/CROSSLINE corrdinates to CDP system. """
A usage example won't hurt

2020-08-27 10:27 UTC, merged