add hdf5 to sgy function
gazprom-neft/seismiqb pull request #34
Opened 2020-08-22 14:02 UTC by dmylzenova

This PR proposes making inference on a whole cube while dumping results to hdf5 and converting hdf5 to segy.

2020-08-24 21:58 UTC, dmylzenova commented on seismiqb/src/geometry.py
> +            Path to load hdf5 file from. File must have a `cube` key where cube data is stored.
Why?

2020-08-24 22:14 UTC, dmylzenova commented on seismiqb/src/geometry.py
> +                            idx = self.dataframe['trace_index'][(il, xl)]
This method belongs to SeismicGeometrySEGY which loads a dataframe with initialization, doesn't it?

2020-08-25 05:25 UTC, SergeyTsimfer requested changes

2020-08-25 05:25 UTC, SergeyTsimfer commented on seismiqb/src/geometry.py
> +                            idx = self.dataframe['trace_index'][(il, xl)]
Sorry, I did not notice this as I was sure this method belongs to `SeismicGeometryHDF5`; yet I think that it is a better place for it.
To this end, I've added `segy_path` attribute which is preserved after converting to `HDF5`; this allows you to retrieve the spec of the original file. Also, I believe that you don't need this `dataframe` as you don't need `idx`

2020-08-25 21:45 UTC, SergeyTsimfer commented on seismiqb/src/geometry.py
> +    def make_sgy(self, hdf5_path='temp.hdf5', segy_path=None, dst=None, postfix='', remove_hdf5=False, zip_result=True):
`path_hdf5`, `path_segy`, `path_spec`?

2020-08-25 21:45 UTC, SergeyTsimfer commented on seismiqb/src/geometry.py
> +        """ Save `.hdf5` cube without headers in `.segy` format with current geometry headers.
```
Convert HDF5 cube to SEG-Y format with current geometry spec
```

2020-08-25 21:45 UTC, SergeyTsimfer commented on seismiqb/src/geometry.py
> +        with h5py.File(hdf5_path, 'r') as src:
Newlines are a blessing

2020-08-25 21:45 UTC, SergeyTsimfer commented on seismiqb/src/geometry.py
> +        dst = dst or (os.path.splitext(hdf5_path)[0] + postfix + '.sgy')
Maybe `os.path.splitext(self.path)`?

2020-08-26 15:59 UTC, dmylzenova commented on seismiqb/src/geometry.py
> +    def make_sgy(self, hdf5_path='temp.hdf5', segy_path=None, dst=None, postfix='', remove_hdf5=False, zip_result=True):
If propose `path_segy` instead of `dst` and `path_spec` as a name for segy cube to load spec from - it is a bit confusing, because the default for  `path_spec`  will be  `self.segy_path`

2020-08-26 16:05 UTC, dmylzenova commented on seismiqb/src/geometry.py
> +        dst = dst or (os.path.splitext(hdf5_path)[0] + postfix + '.sgy')
No, because you would rather want to save segy file next to the hdf5 file you convert it from and not to the folder with the seismic cube itself.

2020-08-26 16:06 UTC, dmylzenova commented on seismiqb/src/geometry.py
> +        with h5py.File(hdf5_path, 'r') as src:
Not sure why you said that but I added a blank line here.

2020-08-26 19:22 UTC, SergeyTsimfer approved these changes
How did you test this function?

2020-08-26 19:22 UTC, SergeyTsimfer commented on seismiqb/src/geometry.py
> +    def make_sgy(self, path_hdf5='temp.hdf5', path_spec=None, path_segy=None, postfix='',
Make `path_segy` one of the last arguments, so you know that it is not needed that often;
The default `temp.hdf5` should be in the same directory, as `self`;

2020-08-27 22:03 UTC, SergeyTsimfer approved these changes

2020-08-27 22:03 UTC, merged