Add rectified surfaces
gazprom-neft/seismiqb pull request #39
Opened 2020-09-24 16:32 UTC by cdtn

2020-09-29 18:11 UTC, SergeyTsimfer commented on seismiqb/src/rectified.py
> +            depth_range = range(horizon.h_min, horizon.h_max)
This is not a good way of separating horizons. Suppose you have two horizons, following each other, but one is 5 units below the other. They would have quite similar (and overlapping) ranges, so you will get an error during the `load_crop` method.

2020-09-29 18:11 UTC, SergeyTsimfer commented on seismiqb/src/rectified.py
> +        self.window = window if window is not None else self.window
`window or self.window`

2020-09-29 18:11 UTC, SergeyTsimfer commented on seismiqb/src/rectified.py
> +class RectifiedSurface(Horizon):
I actually think that you don't need this class at all, neither you need the new method of `add_mask` in the `Horizon` class. All you need to do is to add the option of summing the mask along the `h`-axis in the `create_masks` action of `CropBatch`, as you proposed earlier.

2020-10-08 10:24 UTC, cdtn commented on seismiqb/src/cubeset.py
> +    def load(self, label_dir=None, filter_zeros=True, dst_labels='labels',
https://github.com/gazprom-neft/seismiqb/issues/17#issuecomment-705478606

2020-10-09 10:27 UTC, SergeyTsimfer requested changes

2020-10-09 10:27 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +        along_nearest_horizon : bool
Describe the logic in the first part of the docstring, before parameters

2020-10-09 10:27 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +    def get_nearest_horizon(self, ix, src_labels, heights_slice):
closest horizon?

2020-10-09 10:27 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +        nearest_horizon_ind = np.argmin([horizon.h_mean - location_h_mean for horizon in self.get(ix, src_labels)])
you need to take `absolute` value

2020-10-09 10:27 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +            rectify = True
Make `rectify` separate parameter; move `along_closest` to the `indices` logic

2020-10-09 10:27 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
>          mask = np.zeros((shape_), dtype='float32')
Create maks with shape based on `rectify`

2020-10-09 10:27 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> -
😡

2020-10-09 10:27 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +                self._horizons_matrices[ix] = np.stack([horizon.matrix for horizon in self.labels[ix]])
Horizons can have `matrices` of different shapes

2020-10-09 10:27 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +            horizon_num = 0 if horizon_num is None else horizon_num
Make the default `0`

2020-10-09 10:27 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def add_to_mask(self, mask, locations=None, width=3, alpha=1, rectify=False, **kwargs):
Looks messy

2020-10-09 10:27 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def load_crop_along(self, location, window, offset, **kwargs):
Add the un-cached version of this method

2020-10-09 10:27 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        location : iterable of at least 2 slices
`sequence`; you don't need it to be iterable

2020-10-09 23:13 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +        indices = [indices] if isinstance(indices, int)
That would break something

2020-10-09 23:13 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +        along_nearest_horizon : bool
Still think it should just be a mode of `indices` : `nearest`

2020-10-09 23:13 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +        crop_shape = (crop_shape[0], crop_shape[1], 1) if rectify else crop_shape
`(*crop_shape[:2], 1)`

2020-10-09 23:13 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +    def masks_to_horizons(self, ix, src_masks='masks', src_locations='locations', dst='predicted_labels',
Previous line splits actually had meaning behind

2020-10-09 23:13 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +from matplotlib import pyplot as plt
![image](https://user-images.githubusercontent.com/47103382/95638427-42b16f80-0a9d-11eb-963a-0466aaae0dbe.png)

2020-10-09 23:13 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +    def show_grid(self, plot_over=0, plot_dict=None):
This looks exactly like that thing that should be added to the `plotters.py`, not here

2020-10-09 23:13 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def add_to_mask(self, mask, locations=None, width=3, alpha=1, rectify=False, **kwargs):
`rectify` - > `2d`
Better yet, `mode = '3d'`

2020-10-09 23:13 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
You are doing a lot of unnecessary things in case of `2d` mask; you could return the value right here

2020-10-09 23:13 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    # to allow direct calls of that method that won't be cached.
Thinking emoji

2020-10-09 23:13 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +            data = self.get_cube_values(window, offset, **kwargs)
When I was talking about the non-cached version, I meant using the cube to get the crop, not loading everything along the horizon

2020-10-10 22:56 UTC, cdtn commented on seismiqb/src/crop_batch.py
> +        along_nearest_horizon : bool
Both `load_cubes` and `create_masks` should have same argument indicating that rectified crop creation mode is on.
Naming this arg `indices` is quite confusing.

2020-11-06 05:12 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +                binarize = np.vectorize(lambda x: 0 if x < 0 else alpha)
You are compiling this function at each call to `add_to_mask`. I believe something like 
```
(overlap >= 0).astype(np.int32) * alpha
```
should do the trick

2020-11-06 05:12 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def crop_matrix(self, matrix, location, **kwargs):
It is hard to guess here or in `CropBatch` actions that `matrix` is actually a string. `src`, maybe?

2020-11-06 05:12 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        matrix = self.full_matrix[..., np.newaxis]
This addition of a new axis should be part of the `load_crops` action

2020-11-06 05:12 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +    def load_crops(self, ix, dst, matrix, src_locations='locations',
`load_attribute`, maybe?

2020-11-06 05:12 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        self._cube_values_along = None
Not used anymore

2020-11-06 05:12 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def get_heights_matrix(self, scale=True):
Make it a property

2020-11-06 05:12 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def crop_matrix(self, matrix, location, **kwargs):
Rename to `get_attribute` and default values for arguments: 

- 'amplitudes' for `src`
- `None` for `location`: by default, you produce a map of the desired attribute on the whole cube

2020-11-06 05:12 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        return metrics[..., np.newaxis]
This new axis should also be in `load_crops` action of `CropBatch`

2020-11-16 15:51 UTC, cdtn commented on seismiqb/src/horizon.py
> +    def crop_matrix(self, matrix, location, **kwargs):
IMO, default param for function with `get_attribute` name is kinda counterintuitive. What exactly does one should expect to get when called without any params? I say `ValueError`.

2020-11-16 15:51 UTC, cdtn commented on seismiqb/src/horizon.py
> +    def get_heights_matrix(self, scale=True):
What for? There is `Horizon.full_matrix` already. The function here fulfills two purposes:
1. Makes heights normalization optional.
2. Makes data access cacheable.

When converted to property, it won't longer be able to be parameterized.
However, I can add the following, if you wish:

`heights_matrix = property(cached_get_heights_matrix)`

2020-11-17 04:30 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +        If `component` has an entry from `DATASET_ATTRIBUTES` than retrieve it
then

2020-11-18 06:46 UTC, SergeyTsimfer requested changes

2020-11-18 06:46 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> -        phase = np.unwrap(np.angle(analytic))
Current implementation computes the phase or frequency by the well-known formulae. This method has nothing to do with that and should be implemented in a separate method

2020-11-18 06:46 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +    def reset_caches(self, attrs=None, cubes=None):
Do you see a use case for the `cubes` argument? Especially knowing that the cache is common for all the instances of, say, `SeismicGeometry`.
Let's not bring entities unless we need them and see their usage

2020-11-18 06:46 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +            horizon = self.labels[cube_name][horizon] if isinstance(horizon, int) else horizon
I think that it is easy enough for a person to pass `horizon.h_mean` to the arguments, and there is no need for `horizon` argument

2020-11-18 06:46 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +                idx_i, idx_x = np.asarray(zero_trace_check & heights_check).nonzero()
The previous syntax is looking way better: you can see the checks one after the other

2020-11-18 06:46 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +                for offset in range(width):
`offset` is reserved in seismic applications for something else; use `shift`

2020-11-18 06:46 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def get_cube_values(self, window=23, offset=0, scale=False, chunk_size=256, nan_zero_traces=True, cached=False):
`cached` is not used?

2020-11-18 06:46 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def get_heights_matrix(self, scale=True):
Are you actually using both versions of this matrix? Scaled and unscaled one
If not, keep one of them, and then it definitely should be a property
And you don't need the `heights` prefix in the name; `scaled_matrix` is fine

2020-11-18 06:46 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        """Make crops from data cut along the horizon.
Only knowing in advance what this method is for allows understanding of what is going on in that docstring

2020-11-18 06:46 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def cube_values(self):
Keep the old name and make a new alias
`cube_values` is very vague and misleading, imo

2020-11-18 06:46 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def phases(self):
That is as misleading as it gets. While I can see the logic behind adding `cube_values` property, the `geometry` attribute describes, well, geometry of the object: it has nothing to do with the actual values inside the `SEG-Y` or `HDF5` file and the burden of knowing which cube is which is on the user.
As this attribute in 99% of cases does not evaluate to actual `phases_along_horizon`, this should not be here

2020-11-18 06:46 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +            if attr.startswith('cached'):
A better way to check it is to verify that `isinstance(attr, LRUCache)` and then use `reset`

2020-11-18 11:34 UTC, cdtn commented on seismiqb/src/crop_batch.py
> +    DATASET_ATTRIBUTES = ['label', 'geom', 'fan', 'channel']
I agree that `SeismicCropBatch.get` logic should be modified, but it has nothing to do with current PR, actually

2020-11-18 11:43 UTC, cdtn commented on seismiqb/src/crop_batch.py
> +                     use_labels='all', mode='auto', thicken=3):
I'm ok with keeping `width` (though naming is kinda vague), but as for `index` — to an external user reading pipeline actions it's totally unobvious what it stands for. Cube index? Label index? Locations index? Or is it about some horizon internal attribute? Definitely should be changed to something more obvious and self-documenting.

2020-11-18 11:45 UTC, cdtn commented on seismiqb/src/crop_batch.py
> +        final_ndim : 2 or 3
Not self-explaining at all.

2020-11-18 11:54 UTC, cdtn commented on seismiqb/src/cubeset.py
> +    def reset_caches(self, attrs=None, cubes=None):
The fact that cache is shared between class instances is a flaw, not a feature. Therefore it is expected to be fixed sometime. When it does, `reset_caches` should iterate all cubes anyway. I say one rather obvious extra statement does not make the code more difficult to maintain, and at the same time makes it more flexible.

2020-11-18 16:28 UTC, cdtn commented on seismiqb/src/horizon.py
> +    def phases(self):
Having an attribute in `Horizon` that stores values of loaded cube under `amplitudes` name is even more misleading, than having `phases` standing for the same as `amplitudes`. I can only suggest to get rid of both of them, keeping `cube_values` attribute only.

2020-11-18 16:40 UTC, cdtn commented on seismiqb/src/horizon.py
> +    def get_heights_matrix(self, scale=True):
Current `lru_cache` is inapplicable to properties. So this change will slowdown pipeline run a bit.

2020-11-18 16:54 UTC, cdtn commented on seismiqb/src/horizon.py
> +            if attr.startswith('cached'):
`attr` itself is never instance of `lru_cache`, neither are any of its attributes, added by decoration.
Can do this check instead: `if callable(attr) and hasattr(attr, 'cache')`.

2020-11-18 17:03 UTC, cdtn commented on seismiqb/src/horizon.py
> +            if attr.startswith('cached'):
Or maybe I shouldn't. Calling `getattr(self, attr)` will invoke every lazy calculation possible.

2020-11-18 17:21 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def get_heights_matrix(self, scale=True):
Why is not it applicable?
Anyways, if you use the `cache` decorator, and only then the `property` one, it will work

2020-11-19 10:07 UTC, cdtn commented on seismiqb/src/horizon.py
> +    def get_heights_matrix(self, scale=True):
It doesn't work ¯\\\_(ツ)_/¯. If you first decorate function with `@property` and then with `@lru_cache(1)`, nothing happens. And if `lru_cache(1)` goes before `@property`, than it fails with error due to its implementation details.

As for `cache`, it's introduced in `python 3.9`. And even though it's just a special case of `functools.lru_cache`
```
def cache(user_function, /):
    'Simple lightweight unbounded cache.  Sometimes called "memoize".'
    return lru_cache(maxsize=None)(user_function)
```
substituting our thread-safe `@lru_cache` with `@functools.lru_cache(maxsize=None)` also doesn't work.

2020-12-02 11:32 UTC, SergeyTsimfer approved these changes
I think it is time to better structure the code for the evaluation of geological attributes. This is to be done in a separate PR; as of now, I envision the `GeologicalAttributesMixin` class to contain all of those attributes with a more well-thought interface and re-usage of the same routines, as in `Metrics` (like phase evaluation).

2020-12-02 11:32 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        Although the function can be used in a straightforward way as described above, originally it was implemented
`Although ..., the main usage is...`
The story is nice, but not needed in the docstring

2020-12-02 11:32 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def get_instantaneous_phase(self, window=23, depths=slice(None), normalize=False, use_cache=False, **kwargs):
Feeling somewhat uneasy about the difference in default values for `depths` in methods

2020-12-02 11:32 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def get_instantaneous_phase(self, window=23, depths=slice(None), normalize=False, use_cache=False, **kwargs):
And `use_cache` is better be set to default `False` logic by using `apply_by_default` parameter of cache initialization

2020-12-02 11:32 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +    Class defining decorated attribute must have `_cached_attributes` attribute, to allow tracking cached methods.
You can create this sequence yourself, if you need it.
As a side note: you can actually iterate over class attributes without evaluating any of the properties by using `isinstance(attr, property)` check.

2020-12-02 11:39 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +    """ Recursively unwrap nested tuple, list or dictinary. """
typo
Add explanation of how various containers are flattened.
`obj` -> `iterable`

2020-12-02 13:06 UTC, cdtn commented on seismiqb/src/horizon.py
> +        normalize : str or dict
Due to possible name collision. For example, some `Horizon` functions take `fill_value` argument. If weaved into its logic, `normalize_by_binary_matrix` will be forced to share the value of this argument with the outer function.

2020-12-02 13:14 UTC, cdtn commented on seismiqb/src/horizon.py
> +    def get_instantaneous_phase(self, window=23, depths=slice(None), normalize=False, use_cache=False, **kwargs):
> Feeling somewhat uneasy about the difference in default values for `depths` in methods

IMO, `None` default is even more counterintuitive than `'mid'`.

2020-12-02 13:15 UTC, cdtn commented on seismiqb/src/horizon.py
> +        Although the function can be used in a straightforward way as described above, originally it was implemented
I think, we still need it to explain why this function is implemented. Though, can be reworded a bit.

2020-12-02 13:49 UTC, cdtn commented on seismiqb/src/crop_batch.py
> +        use_labels : str, int or sequence of ints
<details> 
  <summary>1</summary>
  <img src="https://user-images.githubusercontent.com/53620809/100880337-a5335480-34bd-11eb-939b-015a6c174d4e.png">
</details>

<details> 
  <summary>2</summary>
  <img src="https://user-images.githubusercontent.com/53620809/100880371-af555300-34bd-11eb-914e-26f275918953.png">
</details>

<details> 
  <summary>3</summary>
  <img src="https://user-images.githubusercontent.com/53620809/100880426-c4ca7d00-34bd-11eb-883c-22a2c3974d32.png">
</details>

2020-12-14 11:49 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        values = arr[np.where(mask)]
Do you actually need `np.where` here?

2020-12-14 11:49 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        arr[np.where(~mask)] = fill_value
`np.where` not needed

2020-12-14 11:49 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        if nan_zero_traces:
That (almost) can be done via `transform_by_binary_matrix`

2020-12-14 11:49 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def transform_by_binary_matrix(self, arr, transform='min-max'):
`transform_matrix`?
Normalize given by matrix where the horizon is

2020-12-14 11:49 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +    def get_instantaneous_amplitude(self, window=23, depths=None, transform=False, **kwargs):
`amplitudes`?

2020-12-14 11:49 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        Keep in mind, that hilbert transform produces artifacts at signal start and end. Therefore if you want to get
`Hilbert`

2020-12-14 11:49 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        matrix = self.put_on_full(**kwargs)
Add the positional/kw argument of `what to transform`

2020-12-14 11:49 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +def tuplize_nested(iterable):
I believe that the `flatten` word can be helpful

2020-12-14 11:49 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +            result.append((key, tuplize_nested(value)))
`key` can be `tuple` too

2020-12-15 15:50 UTC, cdtn commented on seismiqb/src/cubeset.py
> +        labels_class = type(self[idx, src_labels, 0]).__name__
https://github.com/gazprom-neft/seismiqb/issues/17#issuecomment-744354533

2020-12-23 14:18 UTC, SergeyTsimfer reviewed
Makes me think about a separate child of `Cubeset` to avoid clutter in the current class

2020-12-23 14:18 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +    def show_labels(self, indices=None, main_labels='labels', overlay_labels=None, attributes=None, correspondence=None,
Let's leave it for a future PR

2020-12-23 14:37 UTC, cdtn commented on seismiqb/src/cubeset.py
> +    def show_labels(self, indices=None, main_labels='labels', overlay_labels=None, attributes=None, correspondence=None,
Let's keep it here and fix later if needed.

2020-12-23 14:39 UTC, cdtn commented on seismiqb/src/horizon.py
> +        """ Binary matrix in cubic coordinate system. """
So as `Horizon.full_matrix` doc.

2020-12-23 14:42 UTC, cdtn commented on seismiqb/src/horizon.py
> +        fill_value : any value compatible with `arr.dtype`
Well, it can be `np.unicode_` one day... Is it a `number`?

2020-12-23 14:44 UTC, cdtn commented on seismiqb/src/horizon.py
> +        normalize : 'min-max', 'mean-std', 'shift-rescale' or False
Comment purpose not understood. If you think `None` is a better option than `False`, just say it.

2020-12-23 14:58 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        normalize : 'min-max', 'mean-std', 'shift-rescale' or False
The syntax of docstring is different

2020-12-23 15:22 UTC, cdtn commented on seismiqb/src/utils.py
> +    with open(path, mode) as file:
This is outdated, like, three commits ago.

2020-12-23 15:24 UTC, cdtn commented on seismiqb/src/utils.py
> +    """ Pop variables from kwargs that are meant for function. """
> Signature should be `function, dictionary`: no unpacking here (and at the calls)

Comment is outdated.

2020-12-23 15:31 UTC, cdtn commented on seismiqb/src/utils.py
> +def to_nested_tuple(iterable):
This will make possible future inspection of cache keys more puzzling.

2020-12-23 15:32 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
> +        fill_value : any value compatible with `arr.dtype`
If it is to become anything but a `int`/`float`, which are `number`, we would have much bigger problems to worry about

2020-12-23 15:32 UTC, cdtn commented on seismiqb/src/utils.py
> +    Store loaded slides by default:
Why?

2020-12-24 11:34 UTC, SergeyTsimfer approved these changes

2020-12-24 11:34 UTC, SergeyTsimfer approved these changes
Somewhat useful PR: merging

2020-12-24 11:34 UTC, merged