Load dump
gazprom-neft/seismiqb pull request #41
Opened 2020-10-20 12:07 UTC by a-arefina

This PR introduces possibility to write and read data from hdf5 seismic cubes, that contain only several of 'cube', 'cube_h', 'cube_x' and fixes an error in `make_sgy`

What is DONE
* `make_sgy` writes only those traces, that were present in the original sgy. Before, if some traces were absent, they were filled with zero in hdf5, and it resulted in different number of traces in hdf5 and sgy.spec of the original file, that leaded to crushing when writing new sgy
* `make_sgy` can work with any of 'cube', 'cube_h', 'cube_x' that is present in given hdf5
* `make_hdf5` can create only specified cubes
* tests that checks `make_hdf5` and `make_sgy`

What is still NOT DONE
* load_slide, __getitem__, load_crop of  HDF5 SeismicGeometry still need all 3 cubes to be present
* test data, that is suitable to be put on github

Please have a look and say, if you need this work to be finished

2020-10-21 10:57 UTC, AlexeyKozhevin requested changes

2020-10-21 10:57 UTC, AlexeyKozhevin commented on seismiqb/src/geometry.py
>          Parameters
Extend docstring

2020-10-21 10:57 UTC, AlexeyKozhevin commented on seismiqb/src/geometry.py
>          Parameters
Also update docsting

2020-10-21 10:57 UTC, AlexeyKozhevin commented on seismiqb/src/geometry.py
> +            if 'i' in cubes or 'h' in cubes:
Confused branching and descriptions.

2020-10-21 18:48 UTC, SergeyTsimfer commented on seismiqb/src/tests/dump_test.py
> +    """ Checks that two SEG-Y files contain exacly same traces
Typo

2020-10-21 18:48 UTC, SergeyTsimfer commented on seismiqb/src/tests/dump_test.py
> +def compare_segy_files(path_1, path_2):
Headers should also be compared

2020-10-21 18:48 UTC, SergeyTsimfer commented on seismiqb/src/geometry.py
> +                def get_traces(i, x):
Don't create inner functions: remember axis and use them later for `slice` creation

2020-10-21 18:48 UTC, SergeyTsimfer commented on seismiqb/src/geometry.py
> +                raise ValueError("from cubes == " + from_cubes +
We use f-strings all over the library, so don't hesitate to do that too:)

2020-10-21 18:48 UTC, SergeyTsimfer commented on seismiqb/src/geometry.py
> +    def make_hdf5(self, path_hdf5=None, postfix='', store_meta=True, cubes='ixh'):
`cubes` -> `projections`

2020-12-08 11:33 UTC, AlexeyKozhevin requested changes

2020-12-08 11:33 UTC, AlexeyKozhevin commented on seismiqb/src/cubeset.py
> +    def add_geometries_targets(self, paths, dst='geom_targets'):
Add into `load` possibility of target loading (in the same manner as labels loading)

2020-12-08 11:33 UTC, AlexeyKozhevin commented on seismiqb/src/cubeset.py
>      def convert_to_hdf5(self, postfix=''):
Add `kwargs` to forward to `SeismicGeometry.make_hdf5`

2020-12-08 11:33 UTC, AlexeyKozhevin commented on seismiqb/src/geometry.py
> +    def make_hdf5(self, path_hdf5=None, postfix='', unsafe=True, store_meta=True, cubes='ixh', bar=True):
what do you think about renaming `cubes` to `projections`?

2020-12-08 11:33 UTC, AlexeyKozhevin commented on seismiqb/src/cubeset.py
> +        """Create targets from given cubes
```suggestion
        """ Create targets from given cubes
```

2020-12-16 10:25 UTC, closed without merging