Faults
gazprom-neft/seismiqb pull request #46
Opened 2020-12-02 14:52 UTC by AlexeyKozhevin

2020-12-16 10:02 UTC, AlexeyKozhevin commented on seismiqb/src/cubeset.py
> +            crop = crop[tuple(crop_slice)]
Because `crop_slice` is a list initially:
`Using a non-tuple sequence for multidimensional indexing is deprecated use 'arr[tuple(seq)]' instead of 'arr[seq]'`

2020-12-16 10:02 UTC, AlexeyKozhevin commented on seismiqb/src/cubeset.py
> +        denum = np.zeros(self.geometries[idx].cube_shape[:-1])
I think that my definition is more clear

2020-12-16 11:26 UTC, SergeyTsimfer requested changes
It would definitely help to split this PR into the logic parts

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +    def close(self):
It should be either in `__del__`, which is complicated, or it would be ~never called

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +    def close(self):
Also, there is a `SafeIO` wrapper in our `utils`

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +    def optimal_cube(self, locations):
Let's keep method names verb-like: `get_optimal_projection`, for example

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +    def optimal_cube(self, locations):
The order of methods is quite hard to read

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +    def __getitem__(self, key):
Despite it being magic, docstring for this method is very welcome

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +        slices = np.array(key)[self.STRAIGHT[projection]]
guessing what is going on with the indexing just by looking at the names is virtually impossible; the same with the next line

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +        crop = self.get_cube(projection)[slices[0], slices[1], slices[2]].transpose(self.TRANSPOSE[projection])
Should not `[tuple(slices)]` work just fine?

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +        return self.load_crop(locations, **kwargs)[tuple(slc)]
`load_slide` should definitely use the `cached_load_slide`; it is way faster (due to the absence of `np.stack`) and convenient

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +    def optimal_cube(self, locations):
That really does not do what is promised in the docstring; also, you've lost an entire section of code that allows you to pass triplet of slices directly to the underlying cube which is in some cases way faster (recall the `native` and `custom` modes of `load_cubes` action to speed up the 3d data loads)
This is now a `choose optimal cube orientation for the fastest slide loading`, no more

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +    def optimal_cube(self, locations):
Also, the docstring does not specify that it looks only in existing projections, which is the important part of this method

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +                        for iline in range(ilines.start or start, ilines.stop or stop)])
add the `axis=0` here

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +                        for iline in range(ilines.start or start, ilines.stop or stop)])
the indent is not correct: one more space needed

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +    def get_cube(self, projection):
store all the handlers to data in `self.handlers` dictionary with both `0` and `i` keys available

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +        return self.load_crop(locations, **kwargs)[tuple(slc)]
If anything, it is `load_crop` should use `load_slide` under the hood, whenever possible

2020-12-16 11:26 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +def parse_axis(axis, index_headers=None):
All of the previous comments eliminate the need to move this function away from `geometry` it belongs to: keep in mind, that axis is a `geometry` specific thing and should relate only to the headers

2020-12-16 11:36 UTC, SergeyTsimfer commented on seismiqb/src/hdf5_storage.py
> +        return self.load_crop(locations, **kwargs)[tuple(slc)]
Also, as the current implementation of `lru_cache` can work with `use_cache` argument to disable caching, there is no need for the `cached_load_slide` function at all

2020-12-18 10:24 UTC, AlexeyKozhevin commented on seismiqb/src/crop_batch.py
> +        result = np.zeros_like(image)
It was needed when `attr_filter` was a numba method.

2020-12-18 14:35 UTC, AlexeyKozhevin commented on seismiqb/src/geometry.py
> +    def compute_attribute(self, attr, dst, chunk_shape=None, chunk_stride=None, window=10,
`Geometry.compute_attribute` -> `Geometry.create_attribute_hdf5`
`Geometry.apply_conv` -> `Geometry.compute_attribute`
`utils.attr_filter` -> `utils.compute_attribute`

2021-01-11 10:07 UTC, SergeyTsimfer commented on seismiqb/src/fault.py
> +    [type]
🤔

2021-01-11 10:07 UTC, SergeyTsimfer commented on seismiqb/src/fault.py
> +def thick(points):
`thicken_line`?

2021-03-26 11:46 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +                    normalized = np.zeros_like(data)
```python
normalized = data
```

2021-03-26 11:46 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +    def normalize(self, ix, mode='minmax', stats='geometry', src=None, dst=None, q=(0.01, 0.05)):
That is a strange choice of default quantiles

2021-03-26 11:46 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +    def add_channels(self, crop, channels='first'):
Current implementation:

- splits the component of a batch into separate items
- applies `expand_dim` to each of them
- stacks items back to (N, ...) array

The first and especially the last operations are redundant and time-consuming

2021-03-26 11:46 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +            if crop.ndim == 4:
It is better to apply this transformation before passing the `crops` list to this method

2021-03-26 11:46 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +            background[tuple(background_slice)] = np.nanmax([crop, previous], axis=0)
That is some strange axis magic: `nanmax` is not element-wise function

2021-03-31 09:19 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +    def create_masks(self, ix, dst, src_labels='labels', src_locations='locations',
Is that necessary?

2021-03-31 09:19 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +    def compute_attr(self, ix, dst, src='images', attribute='semblance', window=10, stride=1, device='cpu'):
`compute_attribute`?

2021-03-31 09:20 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +            [description], by default -1
There is no such parameter

2021-03-31 09:21 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +        stats : 'geometry' or 'item'
Maybe, parameter `batchwise=True/False` is more intuitive?

2021-03-31 09:21 UTC, SergeyTsimfer commented on seismiqb/src/crop_batch.py
> +            What quantiles to compute.
Which

2021-03-31 09:27 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> -            map_[label.points[:, 0], label.points[:, 1]] += 1
Can we change the iterator?

2021-03-31 09:28 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +    def _crop_positions(self, cube_name, crop_shape, ilines=None, xlines=None, heights=None,
`_make_regular_grid`?

2021-03-31 09:29 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +            if crop.ndim == 4:
As well as filling all the `nan`s

2021-03-31 09:32 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +            Shape of crops. Must be the same as defined in pipeline. Is needed to create grid for each
Maybe, it is better to use `C('crop_shape')` in the pipeline?

2021-03-31 09:33 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +    def make_prediction(self, dst, pipeline, crop_shape, crop_stride, locations=None,
Definitely looks like it should be a part of some `Controller`, not `dataset`

2021-03-31 09:42 UTC, SergeyTsimfer commented on seismiqb/src/fault.py
> +        faults, sizes = split_faults(self.points, cube_shape=tuple(self.cube_shape), pbar=pbar, **kwargs)
Is there a reason for this inner function to not be a part of the class?

2021-04-05 11:36 UTC, SergeyTsimfer approved these changes

2021-04-05 11:36 UTC, merged