Improve metrics
gazprom-neft/seismiqb pull request #47
Opened 2020-12-08 10:01 UTC by SergeyTsimfer

This PR:

- moves function from `utils.py` into separate files (currently, `utils.py` and `utility_classes.py`), as they are taking quite a lot of place and it is hard to navigate in such a ginormous file; it also cleans up `horizon.py`, `metrics.py` and moves some of the functions into `functional.py`

- converts the `njit`-functions to compute metrics (mainly, metrics in a `local` fashion) to a vectorized `NumPy`. That allows for speed-ups on the scale of 100-200%

- fixes the axis of concatenation for aggregation: previously, it was `-1` as more convenient and interpretable, and now it is `0` as it is way faster

- allows for GPU usage in metric computation: all the `NumPy` code is re-written to a device-agnostic `Numpy`/`CuPy` code. That makes the procedure 10-20x times faster 

- adds a new `perturbed` metric, that compares a horizon against a set of randomly shifted ones

TODO:

- [ ] add tests for `Accumulator`

- [ ] add notebooks with speed-up demo

- [ ] remove old metrics (currently left for ease of comparison)

2020-12-14 10:18 UTC, cdtn commented on seismiqb/src/new_metrics.py
> +        # Save for plot/debug
```suggestion
        # Save for plot
```

2020-12-14 10:18 UTC, cdtn commented on seismiqb/src/new_metrics.py
> +                                                      scale=self.scale, chunk_size=self.chunk_size)
```suggestion
                                                      normalize=self.scale, chunk_size=self.chunk_size)
```

2020-12-14 10:18 UTC, cdtn commented on seismiqb/src/utility_classes.py
> +
```suggestion


```

2020-12-14 10:18 UTC, cdtn commented on seismiqb/src/utility_classes.py
> +        return tuple(key)
Must be updated after merging `rekt` into `master`.

2020-12-15 12:36 UTC, roman-kh commented on seismiqb/src/functional.py
> +    if cp is not np:
Create a constant like `USE_CUDA` for clarity

2020-12-16 11:23 UTC, AlexeyKozhevin commented on seismiqb/src/horizon.py
>  @njit
```suggestion
@njit(parallel=True)
```

2020-12-16 19:29 UTC, SergeyTsimfer commented on seismiqb/src/new_metrics.py
> +                                       support_coords[:, 1], s=33, marker='.', c='blue')
For now, I am. There is no strong need in even looking at those points. It is easier to add later with the clear use case in mind,  rather than polluting method with never-to-be-used arguments

2020-12-16 19:30 UTC, SergeyTsimfer commented on seismiqb/src/new_metrics.py
> +                                                      scale=self.scale, chunk_size=self.chunk_size)
🤔

2020-12-16 19:42 UTC, SergeyTsimfer commented on seismiqb/src/horizon.py
>  @njit
Tested this `jit`-compiled filtration against `NumPy` indexing

2020-12-24 21:10 UTC, AlexeyKozhevin commented on seismiqb/src/utility_classes.py
> +    def get(self, final=False):
Why `final`? May be `copy`?

2020-12-24 21:10 UTC, AlexeyKozhevin commented on seismiqb/src/utility_classes.py
> +            value = np.stack(self.values, axis=-1)
```suggestion
            value = np.stack(self.values, axis=self.axis)
```

2020-12-24 21:10 UTC, AlexeyKozhevin commented on seismiqb/src/utility_classes.py
> +            stacked = self.module.stack(self.values, axis=-1)
```suggestion
            stacked = self.module.stack(self.values, axis=self.axis)
```

2020-12-24 21:10 UTC, AlexeyKozhevin commented on seismiqb/src/plotters.py
> +    def save_and_show(fig, show=True, savepath=None, return_figure=False, **kwargs):
Let's always return `fig`

2020-12-24 21:10 UTC, AlexeyKozhevin commented on seismiqb/src/horizon.py
> +    def smooth_out(self, kernel=None, kernel_size=3, sigma=0.8, iters=1, preserve_borders=True, margin=5, **kwargs):
Update docstring

2020-12-24 21:10 UTC, AlexeyKozhevin commented on seismiqb/src/__init__.py
>  """Init file. """
```suggestion
""" Init file. """
```

2020-12-30 09:03 UTC, SergeyTsimfer commented on seismiqb/src/utility_classes.py
> +            self.value[slc] = self.module.minimum(self.value[slc], matrix[slc])
Now it does

2020-12-30 12:53 UTC, cdtn requested changes

2020-12-30 12:53 UTC, cdtn commented on seismiqb/src/new_metrics.py
> +    'green': [[0.0, None, 0.0], [0.33, 0.0, 0.0], [0.66, 1.0, 1.0], [1.0, 0.5019607843137255, None]],
😡

2020-12-31 20:01 UTC, merged