Improve controllers
gazprom-neft/seismiqb pull request #64
Opened 2021-02-09 07:37 UTC by SergeyTsimfer

This PR improves the memory consumption of `Controller`s by fixing the memory leak, as well as adds a number of small changes throughout the code:

- Fix `Numba` strict typing error
- Make `BaseMetrics.evaluate` save more info for introspection
- Correctly pass parameters of `make_grid`

2021-02-09 08:56 UTC, roman-kh requested changes

2021-02-09 08:56 UTC, roman-kh commented on seismiqb/src/controllers/base.py
> +            self.logger(f'{self.__class__.__name__} ::: {uss:2.4f} ::: {msg}')
Logging level should be configurable, preferably at each log call

2021-02-09 08:56 UTC, roman-kh commented on seismiqb/src/controllers/base.py
> +        horizons = self._inference_chunk(dataset=dataset, ranges=(*spatial_ranges, heights_range),
`_inference_chunk` is not descriptive

2021-02-09 08:56 UTC, roman-kh commented on seismiqb/src/controllers/base.py
> +    def _inference_chunk(self, dataset, ranges, pipeline_config, crop_shape,
why not `on_chunk`?
why private?

2021-02-09 08:56 UTC, roman-kh commented on seismiqb/src/controllers/base.py
>      def inference_1(self, dataset, heights_range=None, orientation='i', overlap_factor=2, prefetch=1,
why `_1`? make it clearer

2021-02-10 08:26 UTC, AlexeyKozhevin commented on seismiqb/src/controllers/base.py
>              horizons = method(dataset, orientation=orientation, overlap_factor=overlap_factor,
We have to generalize `BaseController` to use it not only with horizons

2021-02-10 08:26 UTC, AlexeyKozhevin commented on seismiqb/src/controllers/base.py
>          model_pipeline.run(D('size'), n_iters=n_iters + np.random.randint(100),
Can we use some kind of lock to avoid `np.random.randint(100)`?

2021-02-10 08:26 UTC, AlexeyKozhevin commented on seismiqb/src/controllers/base.py
> +    def _inference_chunk(self, dataset, ranges, pipeline_config, crop_shape,
We use name `locations` instead of `ranges` to define some region (e.g. in `Horizon.add_to_mask`)

2021-02-10 08:26 UTC, AlexeyKozhevin commented on seismiqb/src/geometry.py
> +    def make_quality_grid(self, frequencies, iline=True, xline=True, full_lines=True, margin=0, **kwargs):
Add `full_lines` to docstring

2021-02-19 07:38 UTC, merged