Controller refactor
gazprom-neft/seismiqb pull request #67
Opened 2021-02-26 16:20 UTC by SergeyTsimfer

This PR rewrites `BaseController` and derived classes anew. Among other changes, it proposes to:

- use single `config`-dictionary to parameterize the entire run of the controller
- explicitly pass information between methods
- use instances only to hold parameters
- log pretty much every step of `train` and `inference`, with both textual (iteration-wise) info and graphs (resource monitors and horizon maps)

Changes to come: modify derived classes (`Interpolator`, `Enhancer`, `Extender`) and improve `evaluate` method.

2021-03-02 09:55 UTC, cdtn commented on pylintrc
> +        invalid-name, consider-using-generator
Why disable it globally?

2021-03-02 09:55 UTC, cdtn commented on seismiqb/src/controllers/new.py
> +        self.config = Config(copy(self.DEFAULTS))
Why copy?

2021-03-02 09:55 UTC, cdtn commented on seismiqb/src/controllers/new.py
> +        finish_loss = np.mean(model.loss_list[-25:])
Finishing/final?

2021-03-02 09:55 UTC, cdtn commented on seismiqb/src/controllers/new.py
> +
```suggestion

```

2021-03-02 09:55 UTC, cdtn commented on seismiqb/src/controllers/new.py
> +                _, oinfo = hm.evaluate('find_best_match', agg=None)
o?

2021-03-03 09:26 UTC, AlexeyKozhevin requested changes

2021-03-03 09:26 UTC, AlexeyKozhevin commented on seismiqb/src/controllers/new.py
> +    def make_dataset(self, cube_paths=None, horizon_paths=None, horizon=None):
Let's extend it to use it not only with horizons.

2021-03-03 09:26 UTC, AlexeyKozhevin commented on seismiqb/src/controllers/new.py
> +    def make_dataset(self, cube_paths=None, horizon_paths=None, horizon=None):
At least add `labels_class`

2021-03-03 09:26 UTC, AlexeyKozhevin commented on seismiqb/src/controllers/new.py
> +                    horizon_paths = {dataset.indices[0]: glob(horizon_paths)}
What if I want several cubes in the dataset but with the same relative path to labels?

2021-03-03 09:26 UTC, AlexeyKozhevin commented on seismiqb/src/controllers/new.py
> +        self.log_to_file(pformat(pipeline_config.config, depth=2), '末 train_config.txt')
末?

2021-03-23 11:57 UTC, cdtn requested changes
Also:
1. Refactor `01_DEMO_*` notebooks to have only predict pipeline.
2. Replace `model_config` insides with `…` while logging in `BaseController`.

2021-03-23 11:57 UTC, cdtn commented on seismiqb/src/controllers/base.py
> +    def make_savepath(self, *postfix):
```suggestion
    def make_savepath(self, *subdirs):
```

2021-03-26 08:46 UTC, AlexeyKozhevin commented on seismiqb/src/cubeset.py
>              fill_value = np.min(crops)
nanmin

2021-03-26 08:46 UTC, AlexeyKozhevin commented on seismiqb/src/cubeset.py
>              fill_value = np.min(crops)
and also `background[background_slice] = np.maximum(crop, previous)` -> `background[background_slice] = np.nanmax([crop, previous], axis=0)`

2021-03-26 08:51 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
>              fill_value = np.min(crops)
`maximum` is element-wise; we can use `fmax` to ignore `NaN`s, but it is much slower:(

2021-03-26 16:10 UTC, AlexeyKozhevin commented on seismiqb/src/controllers/base.py
> +        pipeline_config = Config({**self.config['train'], **kwargs})
Add `common` level to `DEFAULT_CONFIG` to avoid keys duplication in `train` and `inference`

2021-03-26 16:13 UTC, AlexeyKozhevin commented on seismiqb/src/cubeset.py
>              fill_value = np.min(crops)
So what do you propose to work with crops which possibly can have nans?

2021-03-26 16:27 UTC, AlexeyKozhevin commented on seismiqb/src/controllers/base.py
> +    def train(self, dataset, **kwargs):
It will be nice to add parameter `config` to substitute `config` directly to methods. In that case I can use the controller in Research in the following way: define controller instance before research creation and then add callables from it (`make_dataset`, `train`, ...) to research. If each callable will have `config` parameter then I will have an opportunity to substitute config from domain into callable by `RC()`.

2021-03-26 16:27 UTC, AlexeyKozhevin commented on seismiqb/src/controllers/base.py
> +    def train(self, dataset, **kwargs):
I also think that it will be a good opportunity to add classes to research. Instances of them will be created at the first iteration and then you will call methods of them

2021-03-26 17:38 UTC, SergeyTsimfer commented on seismiqb/src/controllers/base.py
> +        pipeline_config = Config({**self.config['train'], **kwargs})
The idea is to configure each of them completely separate, as explicitly as possible

2021-03-29 10:47 UTC, SergeyTsimfer commented on seismiqb/src/controllers/base.py
> +    def train(self, dataset, **kwargs):
Added the `config` parameter for train/inference methods

2021-03-31 10:12 UTC, merged