Segy creation
gazprom-neft/seismiqb pull request #70
Opened 2021-03-29 11:36 UTC by akoryagin

- Add `make_segy_from_array` that constructs a `segy`-cube from an array
- For now contains nb with making of a volume of synthetic seismic traces

2021-03-31 08:22 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +from segyio import BinField, TraceField
no need for a separate import

2021-03-31 08:22 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +    zip_result : bool
`zip` is fine

2021-03-31 08:22 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +    spec.sorting = kwargs.get('sorting', 2) # 1 stands for xlines sorting while 2 for ilines-sorting
move to signature

2021-03-31 08:22 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +                lens_of_traces.append([len(dst_file.trace[ctr]), len(trace)])
Was it for debugging purposes?

2021-03-31 08:22 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +        ctr = 0
Not needed here, since you know the amount of traces in advance

2021-03-31 08:22 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +    if zip_result:
Probably, should add the option to remove `sgy` file itself after zipping it

2021-04-01 12:45 UTC, SergeyTsimfer commented
Please, make a separate function for synthetic seismic generation, that takes shape (and other parameters), and returns cubes of seismic data / horizons in the volume

2021-04-01 15:40 UTC, akoryagin commented
> Please, make a separate function for synthetic seismic generation, that takes shape (and other parameters), and returns cubes of seismic data / horizons in the volume

2021-04-03 20:05 UTC, SergeyTsimfer requested changes
This is now a working piece of code, which can be easily transformed into a readable and fast one

2021-04-03 20:05 UTC, SergeyTsimfer commented on seismiqb/src/synthetic.py
> +def rickerwave(f, dt):
You can just use it from `scipy`

2021-04-03 20:05 UTC, SergeyTsimfer commented on seismiqb/src/synthetic.py
> +def convolve_3d(rc, w):
I believe that it can be done better/faster

2021-04-12 13:34 UTC, SergeyTsimfer requested changes
Fix comments, please

2021-04-12 13:34 UTC, SergeyTsimfer commented on seismiqb/src/synthetic.py
> +""" Functions for generation of 2d and 2d synthetic seismic arrays.
typo

2021-04-12 13:34 UTC, SergeyTsimfer commented on seismiqb/src/synthetic.py
> +    """ First param is num_surfaces while the second controls how volatile is the curve. Might wanna
Add documentation

2021-04-12 13:34 UTC, SergeyTsimfer commented on seismiqb/src/synthetic.py
> +    rc[..., 1:] = ((v[..., 1:] * rho[..., 1:] - v[..., :-1] * rho[..., :-1]) /
Making separate variables would make this function twice as fast

2021-04-13 09:56 UTC, RisaMagpie commented on seismiqb/src/synthetic.py
> +            vec[low : ] = colors[j]
Wouldn't it be a good idea to make levels as numpy array and try to broadcast this?

2021-04-13 09:56 UTC, RisaMagpie commented on seismiqb/src/synthetic.py
> +    curves = make_surfaces(num_reflections, grid_shape, perturbation_share=perturbation_share, shape=shape)
I think it will look better if keywords are written for all arguments.

2021-04-14 11:15 UTC, akoryagin commented on seismiqb/src/synthetic.py
> +            vec[low : ] = colors[j]
`levels` already are represented by a `numpy-array`.

Speaking of broadcasting - it's a good idea. Unfortunately, advanced indexing doesn't support array of indices on one axis coupled with slicing on another axis.

2021-04-14 21:19 UTC, akoryagin commented on seismiqb/src/synthetic.py
> +    shares = shares if shares is not None else np.ones((n_curves, ))
This will lead to an error when shares is also an array

2021-04-15 12:44 UTC, akoryagin commented on seismiqb/src/synthetic.py
> +def reflectivity(v, rho):
I think it's better to have reflectivity-array computed in a function for readability purposes

2021-04-15 12:44 UTC, akoryagin commented on seismiqb/src/synthetic.py
> +    shares = np.array(shares) / np.sum(shares)
I don't see much difference here

2021-04-15 12:45 UTC, akoryagin commented on seismiqb/src/synthetic.py
> +        raise ValueError('`shape` and `grid_shape` parameters should match.')
True

2021-04-15 12:46 UTC, akoryagin commented on seismiqb/src/synthetic.py
> +    return result
True

2021-04-15 12:48 UTC, akoryagin commented on seismiqb/src/utils.py
> +    n_ilines, n_xlines = heights.shape[0], heights.shape[1]
yup, that's a bit prettier

2021-04-15 12:57 UTC, akoryagin commented on seismiqb/src/utils.py
> +    df = pd.DataFrame(ilines_xlines, columns=['ILINE', 'XLINE'])
ok, that should be a bit faster for large shapes

2021-04-15 13:05 UTC, SergeyTsimfer commented on seismiqb/src/utils.py
> +def make_charisma_from_surface(heights, path):
There is a `Horizon.dump_charisma`, which is a staticmethod for exactly this reason: it can be used without horizon instance whatsoever

2021-04-16 16:03 UTC, merged