Refactor geometry
gazprom-neft/seismiqb pull request #72
Opened 2021-04-09 08:32 UTC by SergeyTsimfer

In this PR:

- `geometry.py` is moved into a separate folder with individual files for various geometry classes
- added option to quantize data during the conversion from `SEG-Y`: to do so, we digitize amplitudes into 256 pre-computed bins
- added `blosc` format: this is a highly effective compression, that takes a lot less memory. The drawback is that it stores individual slides and, therefore, slow for loading 3d chunks of data
- added option to work cubes with missing projections
- QoL additions to geometries: textual and visual representations / properties

2021-04-12 10:08 UTC, a-arefina commented on seismiqb/src/geometry/base.py
> +    def show(self, matrix='snr', **kwargs):
show_attribute/show_matrix/...

simple `show` is a bit obscure

2021-04-12 10:08 UTC, a-arefina commented on seismiqb/src/geometry/base.py
> +        """ Convert POST-STACK HDF5 cube to SEG-Y format with current geometry spec.
do you really need this in this base class? What about a separate function with spec sgy provided as an argument, or `SeismicGeometryHDF5` method?

2021-04-12 10:30 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +    def show(self, matrix='snr', **kwargs):
I wanted to unify the method name with `Horizon`: `horizon.show` and `geometry.show` display top view on that entity and contain relevant info

2021-04-12 10:36 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +        """ Convert POST-STACK HDF5 cube to SEG-Y format with current geometry spec.
I am thinking about moving all the `make_file_from_something` functions to a separate file / mixin

2021-04-12 10:41 UTC, SergeyTsimfer commented on seismiqb/src/geometry/converted.py
> +        return available[0]
That looks great

2021-04-12 10:43 UTC, SergeyTsimfer commented on seismiqb/src/cubeset.py
> +            self.geometries[ix].process(collect_stats=True, spatial=True, **kwargs)
I will make it not as hardcoded

2021-04-12 11:12 UTC, dpodvyaznikov commented on seismiqb/src/geometry/base.py
> +    def show(self, matrix='snr', **kwargs):
I think `describe` is more convex name for this

2021-04-12 11:48 UTC, dpodvyaznikov commented on seismiqb/src/cubeset.py
> +            self.geometries[ix].process(collect_stats=True, spatial=True, **kwargs)
Yep, so far we don't use stats or spatial data anywhere in metrics and we don't want to, since it really slows loading from segy file.

2021-04-13 08:41 UTC, a-arefina commented on seismiqb/src/cubeset.py
> +                if '.dvc' in path:
path.endswith('.dvc') ??

2021-04-13 10:19 UTC, anton-br commented on seismiqb/src/geometry/segy.py
> +        ranges : str
why someone can't calculate the desired quantile from self.trace_container?

2021-04-14 12:35 UTC, akoryagin commented on seismiqb/src/horizon.py
> +        We can control bezier-like and points-like holes amount by `n` and `points_proportion` parameters respectively.
It is hard to understand what do you mean by "points-like holes" without reading the code

2021-04-14 13:08 UTC, akoryagin commented on seismiqb/src/geometry/blosc.py
> +        dataset_name_0/
datasets are basically different cube-projections?

2021-04-14 13:15 UTC, AlexeyKozhevin commented on seismiqb/src/geometry/hdf5.py
> +        """ TODO. """
Add warning

2021-04-14 15:11 UTC, cdtn requested changes

2021-04-14 23:21 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +            key_ += [slice(None)] * (len(self.cube_shape) - len(key_))
That check is for `getitem` specifically, where unspecified axis are last

2021-04-14 23:22 UTC, SergeyTsimfer commented on seismiqb/src/geometry/base.py
> +        self._quality_grid = quality_grid
We can't store cache in `meta`

2021-04-14 23:26 UTC, SergeyTsimfer commented on seismiqb/src/geometry/converted.py
> +        return None
The only reason for this return is to make `pylint` happy; removed it and disabled `pylitn` here

2021-04-14 23:31 UTC, SergeyTsimfer commented on seismiqb/src/geometry/blosc.py
> +        dataset_name_0/
The `BloscFile` uses the same semantics and name conventions, as `HDF5.File`; hence the naming and underlying structure

2021-04-15 13:09 UTC, akoryagin commented on seismiqb/src/geometry/blosc.py
> +        dataset_name_0/
I think it would be great to add something similar "The BloscFile uses the same semantics and name conventions, as HDF5.File" to the class-docstring.

Otherwise, the architecture looks pretty arbitrary and created for solving one specific task despite rather generic naming

2021-04-16 11:25 UTC, merged