Plotter upgrade
gazprom-neft/seismiqb pull request #75
Opened 2021-04-25 16:34 UTC by cdtn

1. Implement concept of "displayed" attributes in `SeismicGeometry`.
2. Upgrade plotter functionality.

2021-04-26 09:04 UTC, SergeyTsimfer requested changes

2021-04-26 09:04 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +            src_key = prefix + dst_key
If `title_fontsize` is None, you should use the `fontsize` key

2021-04-26 09:04 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +            src_key = prefix + dst_key
That would significantly improve the code

2021-04-26 09:04 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +        """ Plot several images on one canvas using matplotlib: render the first one in greyscale
Remove parameters from docstrings: they are unreachable anyways
Maybe, `multi_histogram`?

2021-04-26 09:04 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +        if 'ax' in kwargs:
Move this logic of `create me multiple subplots or used supplied ` or `create me one axis or use supplied` into a separate methods and use it everywhere

2021-04-30 09:01 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +def filter_kwargs(kwargs, keys, index=slice(None), prefix=''):
Don't like the naming: you are not filtering `key-word arguments`, you are filtering supplied dictionary. `filter_parameters`?

2021-04-30 09:07 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +                    'cmap': DEPTHS_CMAP,
```suggestion
                    'cmap': 'Depths',
```

2021-04-30 09:08 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
>          xaxis_kwargs = filter_kwargs(updated, ['xlabel', 'fontsize', 'family', 'color'])
Add `xaxis_` and `yaxis_` prefixes

2021-05-17 12:07 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +                width = updated['horizon_width']
`curve_width`?

2021-05-28 14:36 UTC, cdtn commented on seismiqb/src/horizon.py
> +                          name=f"copy_of_{self.name}")
dont

2021-05-31 09:43 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +        if 'disable_axes' in actions and all_kwargs.get('disable_axes'):
Do you need this listed in `actions`?

2021-05-31 09:43 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +    def process_cmap(cls, params, bad_color):
Not sure about this `inplace` update

2021-05-31 09:43 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +            cmap = ListedColormap(cmap_name)
Raise a `ValueError` if it is not a valid color either

2021-05-31 09:43 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +    def process_cmap(cls, params, bad_color):
`cmap` is retrieved from `params`, while `bad_color` is passed explicitly. Seems inconsistent

2021-05-31 09:43 UTC, SergeyTsimfer commented on seismiqb/src/plotters.py
> +                    'bad_color': (.0,.0,.0,.0)}
can you use `black`?

2021-05-31 09:52 UTC, cdtn commented on seismiqb/src/plotters.py
> +            cmap = ListedColormap(cmap_name)
It's raised by `ColorConverter`.

2021-06-10 10:00 UTC, SergeyTsimfer approved these changes

2021-06-10 11:55 UTC, cdtn commented on seismiqb/src/plotters.py
> +    def nest_data(data, separate):
`nest_data`

2021-06-15 10:53 UTC, SergeyTsimfer approved these changes

2021-06-15 10:53 UTC, SergeyTsimfer commented on seismiqb/src/utility_classes.py
> +    def __init__(self, maxsize=None, attributes=None, apply_by_default=True, copy_on_return=False):
`maybe_copy`?

2021-06-15 18:02 UTC, SergeyTsimfer approved these changes

2021-06-15 18:15 UTC, merged