Facies
gazprom-neft/seismiqb pull request #76
Opened 2021-04-27 07:23 UTC by cdtn

2021-04-28 16:13 UTC, cdtn commented on seismiqb/src/facies.py
> +            storage[k] = defaultdict(list, v)
Not "relies", no. Though, labels from `subsets` should be a subset of those listed by `list_main_labels`.

2021-05-11 13:06 UTC, cdtn commented on seismiqb/src/facies.py
> +                main_labels = labels[0]
Sure. When there is only one labels subdir provided, it's automatically assumed to be "main", since there's no other labels groups around.

2021-05-11 13:17 UTC, cdtn commented on seismiqb/src/facies.py
> +                colors_order = [3, 2, 1, 0, 4, 5, 6, 8, 9, 7]
Because I like the way colors match.

Default seaborn 'muted' palette is ordered in a way the neighboring colors does not look cool together.

![image](https://user-images.githubusercontent.com/53620809/117821267-139def00-b274-11eb-9c90-f13d00496c92.png)

2021-06-09 11:28 UTC, AlexeyKozhevin requested changes

2021-06-09 11:28 UTC, AlexeyKozhevin commented on seismiqb/src/facies/cubeset.py
> +        >>> cubeset.apply_to_labels('smooth_out', ['CUBE_01_XXX', 'CUBE_02_YYY'], ['horizons', 'fans'}, iters=3])
```suggestion
        >>> cubeset.apply_to_labels('smooth_out', ['CUBE_01_XXX', 'CUBE_02_YYY'], ['horizons', 'fans'], iters=3])
```

2021-06-09 11:28 UTC, AlexeyKozhevin commented on seismiqb/src/facies/cubeset.py
> +        """ Call specific function for labels attributes of specific cubes.
It is not clear how does it work: inplace or not? What does it return?

2021-06-09 11:28 UTC, AlexeyKozhevin commented on seismiqb/src/facies/cubeset.py
> +        Make predictions and put them into dataset attribute.
Extend docstring

2021-06-09 11:28 UTC, AlexeyKozhevin commented on seismiqb/src/facies/cubeset.py
> +        pbar = tqdm(self.flatten_labels(src_labels))
You use two prgress bars here but the parameter `bar` refers to only one.

2021-07-16 07:37 UTC, SergeyTsimfer reviewed
I have not checked the `facies/cubeset` and `facies/info` in detail, but the rest of the code looks really clean. 
My suggestion is to leave all the linkage, correspondence and such in `facies/*` directory, but move all of the attribute computation to a separate `Mixin` for Horizon class: we could discuss the naming scheme separately, but I believe that having an option to evaluate geological attributes would be helpful for the general horizon detection task as well.
Also, this way you would not need a separate `Batch` class:)

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/batch.py
> +    def load(self, ix, dst, src='amplitudes', src_labels='labels', res_ndim=3, **kwargs):
Maybe, `load_attribute`?

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/batch.py
> +        elif res_ndim != res.ndim:
Looks somewhat strange -- you asked pipeline to load data and it raises an error depending on your guess on ndim

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/cubeset.py
> +        Make predictions and put them into dataset attribute.
I would much rather prefer explicitly calling insides of this function in your notebook / controller

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/cubeset.py
> +        pbar.set_description("General progress")
General Kenobi?
Anyway, this description is quite useless and is not updated anywhere

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/cubeset.py
> +            label_id = np.where([item.name == label.name for item in labels[label.geometry.short_name]])[0][0]
You would not need this if you just iterated over the indexed dict of `labels` directly

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/cubeset.py
> +            predicted_matrix = expit(accumulator.data).squeeze()
You could just fetch `sigmoid` from the model directly

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/cubeset.py
> +            results[label.geometry.short_name].append(prediction)
Once again, iterating over the indexed dict would make things easier and more clear
Also, why do you need to use `setattr`, if the `name` is hardcoded?

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/facies.py
> +        self.sampler = None
Not needed anymore

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/facies.py
> +    def __init__(self, *args, **kwargs):
List the full signature

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/facies.py
> +        try:
use if-clause, maybe? `try/except` looks really forced here

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/facies.py
> +        """ Make crops from `src` of horizon at `location`.
This extended doc should be in public method, not in private

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/facies.py
> +        if location is not None:
Someday, we would need to re-write attribute loading methods so they use `locations` not to crop the loaded result, but to load attribute only at `location`. Leave a `TODO` message here

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/facies.py
> +        *subsets, src = src.split('/')
What is the use case for more than one subset at a time?

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/facies.py
> +        data = self._load_attribute(src=src, location=location, **kwargs)
I think you could just move insides of the `_load_attribute` method right here, as it is only a few lines

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/facies.py
> +        load : str or dict or np.ndarray, or a list of objects of those types
Unclear name. `src` is better, `what` is better but meh, `*args` is fine but dangerous

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/facies.py
> +        load : str or dict or np.ndarray, or a list of objects of those types
Maybe, `data`

2021-07-16 07:37 UTC, SergeyTsimfer commented on seismiqb/src/facies/facies.py
> +    def draw_crop_grid(self, ax, **kwargs):
Not needed anymore, I suppose? Check that `RegularGrid.show` works fine for you (and move some missing functionality from this method to there, if needed)

2021-07-19 14:40 UTC, cdtn commented on seismiqb/src/facies/facies.py
> +        load : str or dict or np.ndarray, or a list of objects of those types
maybe

2021-07-21 09:13 UTC, SergeyTsimfer approved these changes

2021-07-25 20:59 UTC, merged